### ISSUE TITLE
Implement map/sidebar toggle functionality and API

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1002]
This will be utilized on mobile viewports to toggle whether the map or the sidebar is shown. In reality, it may just be toggling the visibility of the sidebar.

There should be a way to do this programmatically (so that a plugin can do it) and through the UI.

The code may be toggling classes on the map and sidebar that effect the visibility of each item. Those classes should only have an effect on small viewports.

Also, this toggling is designed for single plugin mode, but it may make sense to make it available in any configuration.

**Comment by ajrobbins** [comment]
Designs: [2017_09_25_phone_v1.pdf](https://github.com/CoastalResilienceNetwork/GeositeFramework/files/1340931/2017_09_25_phone_v1.pdf)

**Comment by caseycesari** [comment]
Some issues that came up when I started implementing this:

- Assuming we'll use a media query to show the buttons and hide the map/sidebar initially, we'll have to make sure the programmatic route can override those rules.
- The framework needs some CSS rule revisions to make it more mobile-friendly in general.
- The search element can become collapsed via a configuration option, but how will we know to do this on small screens?
- Regarding the above point, and more in general, how will the JS implementation of this interact with the CSS? Querying for viewport sizes seems fragile. We could add a class to the body when we know the media queries will be in effect, but that will require keeping parts of the code and CSS in sync.

**Comment by kellyi** [comment]
Got a working-ish version of the toggle buttons so far on this branch https://github.com/CoastalResilienceNetwork/GeositeFramework/tree/ki/mobile-super-web-app

![map-content-toggle-buttons](https://user-images.githubusercontent.com/4165523/31360215-5f86f2c0-ad1b-11e7-9def-89752d103225.gif)

Going to give this some thought in advance of discussing it tomorrow:

> The framework needs some CSS rule revisions to make it more mobile-friendly in general.

**Comment by kellyi** [comment]
Dropping this here for possible use:

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

**Comment by kellyi** [comment]
@caseycesari 

Do we want this:

> There should be a way to do this programmatically (so that a plugin can do it) and through the UI.

...to be available both in non-mobile and mobile mode? I assume it should only be available in single plugin mode, but should it always be available otherwise?

**Comment by caseycesari** [comment]
Should be just mobile single-plugin mode for now.
