### ISSUE TITLE
New bug - hamburger menu under left nav

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#1026]
Team - not sure when this started, but see graphic below showing the bug. Tried this on multiple master framework sites. I will try rebuilding...

![screen shot 2017-11-20 at 12 52 30 pm](https://user-images.githubusercontent.com/5605392/33041091-fc2295f2-cdf1-11e7-891d-74c4c405542d.png)

**Comment by caseycesari** [comment]
May be a side-effect of https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/968

**Comment by kellyi** [comment]
Tried reproducing this on my local without success:

<img width="856" alt="screen shot 2017-11-28 at 2 51 25 pm" src="https://user-images.githubusercontent.com/4165523/33341059-b9f637f0-d44b-11e7-8851-52d83444db26.png">

Do see it happening on the site from the issue's original image, though:

<img width="809" alt="screen shot 2017-11-28 at 2 51 34 pm" src="https://user-images.githubusercontent.com/4165523/33341076-c9c5b494-d44b-11e7-8a8b-c6604b9109c5.png">

**Comment by kellyi** [comment]
Tried reverting the change here https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/968 but that didn't fix it.

Dropping the `.nav-apps` zindex below 2800 does fix it, although I don't know what other things that might break:

<img width="1116" alt="screen shot 2017-11-28 at 3 27 50 pm" src="https://user-images.githubusercontent.com/4165523/33342619-b892aa2e-d450-11e7-95c5-f6b72cc1a3c5.png">

**Comment by kellyi** [comment]
`header` and `header .nav-main` have a zindex of 2800:

https://github.com/CoastalResilienceNetwork/GeositeFramework/search?utf8=%E2%9C%93&q=2800&type=

**Comment by kellyi** [comment]
I set up my local instance of the framework to have the same plugins to see whether I could reproduce the bug that way, but wasn't able to recreate it that way.

Going to check into why changing the z-index would fix it and make a PR.

**Comment by zferdana** [comment]
Hi Casey and Kelly - do you have a timeline on this? Would be good to know, as we are launching maps.bluewaysconservation.org tomorrow using framework master. Just let me know - thx

**Comment by kellyi** [comment]
Hi Zach! I managed to reproduce this bug locally and I'm about to put up a pull request to fix it. It should be in `master` by or before 2pm ET tomorrow.
