### ISSUE TITLE
App does not appear in Single App Mode

### ISSUE THREAD

**Issue by cschneebeck** [CoastalResilienceNetwork/GeositeFramework#1043]
- Hawaii region [development branch](https://github.com/CoastalResilienceNetwork/hawaii-region/tree/development)
- region.json specifies [ecological-effects-slc](https://github.com/CoastalResilienceNetwork/ecological-effects-slc/tree/development) as the pluginFolderName
- The site builds successfully, but the app does not load in the left pane and the left pane completely covers the map
- An error is thrown when trying to load underscore.js

![image](https://user-images.githubusercontent.com/11446978/33733512-3d825db8-db47-11e7-9567-7124c6e36138.png)

**Comment by ajrobbins** [comment]
Related to https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/669

**Comment by cschneebeck** [comment]
FYI, to make sure the app wasn't causing the problem, I tested the same region with a different app. I switched ecological-effects-slc out with marsh-explorer and ran the build again. I received the same error trying it with marsh-explorer so I switched it back to ecological-effects-slc.
