### ISSUE TITLE
Create Print documentation

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#1045]
Create documentation for new plugin print and post to wiki,

**Comment by caseycesari** [comment]
@zferdana @lesserj @cschneebeck A first draft of the plugin print workflow is available at https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Plugin-Settings#custom-plugin-print. Let me know if there's anything I can do to improve it. Thanks.

**Comment by caseycesari** [comment]
@matts5517 Meant to include you as well. See the above comment.
