### ISSUE TITLE
Convert pixels to physical units in print stylesheets

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1061]
> 3.  Many styles in the default print stylesheet still use pixels.  For anything print, we should be using physical units like mm, cm, in.  It seems the stylesheet is about 50/50 with physical units and pxs.  This may be the source of some other issues I'm seeing when attempting to size the map and legend elements, but haven't been able to verify yet.

**Comment by kellyi** [comment]
In #1096 I'm devolving most of the app-print-specific style rules into the page-size-specific CSS files, which will make it easier to know which rules have been applied for whichever page size.
