### ISSUE TITLE
Simple way to not show all layers in legend

### ISSUE THREAD

**Issue by cschneebeck** [CoastalResilienceNetwork/GeositeFramework#1069]
I found a very easy way to exclude some layers in the legend. Adding one statement to Legend.js will handle this. Lines 66-68 in the image below simply says if the layer name starts with underscore, don't include it in the legend. Once this statement is added to Legend.js, developers could open the map service's source mxd and append an underscore to any layer that they don't want showing up in the legend. 

I tested this logic while working on the Hawaii region and it works well.

![screen shot 2018-01-22 at 9 00 41 am](https://user-images.githubusercontent.com/11446978/35230270-d51a1fc4-ff52-11e7-95df-8d19f8d07635.png)

**Comment by matts5517** [comment]
Hey Casey,

I am getting the error attached in the image in IE 11. Do you get the same results. 

![screen shot 2018-02-06 at 11 19 47 am](https://user-images.githubusercontent.com/19394069/35876603-fc42885a-0b2f-11e8-968b-3d643d1df0b1.png)

**Comment by ajrobbins** [comment]
Hi @matts5517 after realizing the IE issue you just pointed out, we pushed a version of this to master that uses a different workaround: https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1073/files

**Comment by ajrobbins** [comment]
Addressed in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1073
