### ISSUE TITLE
Print is triggered multiple times

### ISSUE THREAD

**Issue by lesserj** [CoastalResilienceNetwork/GeositeFramework#1072]
The new print feature gets triggered multiple times when clicking the print button.  Best case scenario, this causes the system print window to appear several times after hitting cancel.  If the content insertion in the prePrintModal function uses appends rather than replaces, then content will be inserted multiple times.  I have not been able to figure out the root cause of the issue.  Anecdotally, the region framework has three plugins that have a custom print function, and the print is being called three times.  This may or may not be related.  The number of times it tries to print increases every time the plugin print button is clicked.

![multiple-print-calls](https://user-images.githubusercontent.com/2304500/35453231-46c8f9fa-027e-11e8-9674-b9be8dfa2a8f.gif)

**Comment by kellyi** [comment]
Spent some time trying to figure out how to recreate a minimal version of this bug in advance of reviewing  #1080 and I am able to recreate it by:

- setting up the base GeositeFramework
- adding the regional planning plugin
- setting `"hasCustomPrint": true` in the regional-planning plugin's overrides.json file

Once that's done, clicking the plugin's custom print button seems to create three print windows, and on canceling each of them an error like this is reported in the browser console:

![screen shot 2018-08-29 at 3 46 32 pm](https://user-images.githubusercontent.com/4165523/44811504-d916c580-aba2-11e8-915f-aa28f8bd9995.png)
