### ISSUE TITLE
Chrome JS version bug

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#1081]
A recent change in Chrome caused all older explorer apps to fail, therefore preventing the entire site from loading in chrome. Other browsers like Firefox worked fine. As a band-aid, we removed the problem apps which restored the sites in Chrome, but we need a long term fix. From the error message Casey found below, upgrading from JS 3.11 to 3.24 would likely solve this issue, this upgrade is also needed to bring in openstreetmap as an esri base map option. 

“The page is using the arcgi js API 3.11 (which refers to xstyle). The older xstyle versions do have a bug concerning pseudo-css-elements (they need empty strings as retunr value instead of the correct 'normal'). Chrome v67 now returns the correct 'normal' causing the xstyle APi to raise errors. 
 You should try to upgrade to the arcgis js API version 3.24”

**Comment by caseycesari** [comment]
@laflessn The upgrade to 3.25 has been merged to the `develop` branch. Let us know if this fixes the above reported issue.

**Comment by laflessn** [comment]
I have successfully confirmed and tested this in various regions. Please push to master.

**Comment by caseycesari** [comment]
Thanks @laflessn. I'll let you know when this is in master.
