### ISSUE TITLE
openstreetmap basemap

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#1082]
http://www.OpenStreetMap.org. 
We need to add openstreetmap as a basemap option to list in the region.json. Also confirm the capability and requirements of adding custom basemaps to this list.

**Comment by fungjj92** [comment]
Blocked by #1081

**Comment by caseycesari** [comment]
@laflessn OSM is now a supported basemap option on `develop`. Here's an example of how to add this option: https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/f8da64335cbb697c8e86ca86b68cb40953263e19/src/GeositeFramework/region.json#L81

Also, re:

> Also confirm the capability and requirements of adding custom basemaps to this list.

Can you provide an example of a custom basemap?

**Comment by laflessn** [comment]
I have successfully confirmed and tested this. Please go ahead and push to master. To my knowledge, we don't yet have an example of a custom basemap and Zach will have to provide more detail on his expectations for this.
