### ISSUE TITLE
Migrate region.json validation

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1089]
- Find a python library to validation JSON schemas
- Add this library to the requirements
- Integrate into the development server. Keep in this mind that the validation will need to be run when the project is built through [build.py](https://github.com/CoastalResilienceNetwork/geosite-framework-build/blob/master/build.py).
- Where this code lives: [1](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Helpers/JsonDataRegion.cs), [2](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/App_Data/regionSchema.json)

Depends on #1085

**Comment by kellyi** [comment]
I imagine there may be a webpack loader to do JSON schema validation.

**Comment by fungjj92** [comment]
The top-level issue description has been updated since merging the [ADR](https://github.com/azavea/civic-apps/pull/331/files), going with a python environment (to clarify the above suggested to use webpack/JS)
