### ISSUE TITLE
Include version.txt file with current git sha in static site output

### ISSUE THREAD

**Issue by kellyi** [CoastalResilienceNetwork/GeositeFramework#1093]
To streamline the process of knowing what version of the framework is used for any given deployment, we should add a version.txt file to the static site output bundle containing the branch's head git sha.

**Comment by caseycesari** [comment]
This is something we may want the build tool to generate instead of the framework scripts.

**Comment by caseycesari** [comment]
I think this should be blocked on https://github.com/CoastalResilienceNetwork/geosite-framework-build/issues/37
