### ISSUE TITLE
Remove or reimplement proxy after migrating off IIS

### ISSUE THREAD

**Issue by fungjj92** [CoastalResilienceNetwork/GeositeFramework#1097]
We use a proxy to intercept and adjust requests to ESRI. It runs on IIS currently, and will go away when we switch over to a static site. If its use cases prove essential upon conversion, we'll have to figure out a solution to reinstate the proxy.

Should we have to reinstate the proxy, this issue may connect #1095 which has fall out CORS console errors for getting Calcite icons. They're unsightly and[ potentially solvable ](https://developers.arcgis.com/javascript/3/jssamples/exp_cors_buffer.html)via [the proxy](https://developers.arcgis.com/javascript/3/jshelp/ags_proxy.html). Weirdly, it looks like calcite resources are included in our custom arcgis js api bundle. Fortunately, there's no visible problems in the app and icons are visible. 
![screen shot 2018-08-31 at 4 48 26 pm](https://user-images.githubusercontent.com/10568752/45056356-b08a4200-b060-11e8-852b-2c4bbe650d07.png)
![screen shot 2018-09-04 at 4 15 07 pm](https://user-images.githubusercontent.com/10568752/45056357-b122d880-b060-11e8-8712-c76631e6459b.png)

**Comment by caseycesari** [comment]
A good region to test if the proxy is still required is the gulfmex region. A lot of the plugins make use of the proxy. For example, here are the requests made by the Future Habitat plugin:

![image](https://user-images.githubusercontent.com/1042475/47175370-efa6e680-d2e0-11e8-9a18-2352609f2ae9.png)
