### ISSUE TITLE
Fix broken file paths

### ISSUE THREAD

**Issue by fungjj92** [CoastalResilienceNetwork/GeositeFramework#1108]
With the conversion to a static site in #1085, some assets are returning 403 and 404 because their paths are incorrect. The files that are trying to be brought in via the [backend](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/128f17cb97401d41ee359f33cb06ae99b6804161/src/GeositeFramework/Models/Geosite.cs#L339) remain to be fixed.

![screen shot 2018-09-12 at 4 23 11 pm](https://user-images.githubusercontent.com/10568752/45451294-aa234800-b6a8-11e8-8ed2-192ce5991874.png)

Note the font files and `use.js`

**Comment by caseycesari** [comment]
The use.js error mentioned here is fixed by https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1130, which corrected the `use` config in the index. This card should focus on fixing the icons, though do note that some of the font files do not resolve on the existing site.
