### ISSUE TITLE
Basemap Chrome Issue on Mobile

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#1137]
Confirmed on several mobile OS that you're unable to pan or pinch zoom on esri basemaps using chrome browser. This is a new issue. Is this related to the chrome js fix that was recently implemented?

**Comment by caseycesari** [comment]
Hi @laflessn, I'm unable to reproduce this. Can you provide a site (or sites) where this is happening? And perhaps what device(s) you tested it with? Thanks!

**Comment by laflessn** [comment]
I have a google pixel android device and this is an issue using Chrome on all base maps on coastal resilience super web app sites. However, this wasn't always an issue ... that's why I suspect whatever update we did to fix the JS chrome bug may have broken something else. This occurs on maps.coastalresilience.org/hawaii   and maps.coastalresilience.org/indonesia.  However, the basemaps are functional on same device using firefox.

**Comment by mmcfarland** [comment]
Tested this with 3 versions of Android devices, including a Google Pixel and haven't been able to reproduce the issue described.  Chrome versions 69 & 70.

**Comment by laflessn** [comment]
Confirmed that it's still an issue on Android 9.0 Pixel Build/PPR2  using Chrome 69. Works fine on firefox on same device.  I'm testing on http://maps.coastalresilience.org/hawaii/ and http://maps.coastalresilience.org/indonesia

**Comment by mmcfarland** [comment]
I've been able to reproduce this on a new Android 9.0 Pixel 3 Build/PD1A using Chrome 70.  Firefox works on the same device.

**Comment by mmcfarland** [comment]
This stock esri sample also works correctly on the same device where the it does not on the TNC sites

https://developers.arcgis.com/javascript/3/samples/exp_history/

Note the esri js api version is 3.26 in this example.

**Comment by mmcfarland** [comment]
3.26 changelog:

> BUG-000116101: Fixed an issue when using a touch device and panning in Google Chrome browser using Android 9 OS did not work.


https://developers.arcgis.com/javascript/3/jshelp/whats_new.html

I'll try updating the bundle version.
