### ISSUE TITLE
Suspected framework or Esri JS bug in single-app mode 

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#1142]
Suspected bug at either the framework or ESRI javascript level, found when testing Natural Coastal Protection App in single-app mode. After initial load when the map panel is hidden if a user selects the global extent, the map will attempt to zoom to view the whole planet. Because of the small size of the hidden map component, the map zooms incorrectly and will show a very small, off center map when navigating to the map panel. 

![tnc-global-extent-mobile](https://user-images.githubusercontent.com/11638128/47047395-4f1fbd80-d14c-11e8-90ad-52d9f029834b.gif)

**Comment by fungjj92** [comment]
I was able to reproduce the issue building this region: https://github.com/CoastalResilienceNetwork/coastal-protection-region

Looking into it
