### ISSUE TITLE
Look into reported DR translation issue

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1163]
From TNC:

> Error: Failed to load resource: /dr-secure/languages/es:1  the server responded with a status of 404 ()

**Comment by caseycesari** [comment]
Is the site listed above, `dr-secure`, built off of the `dr-region` repo? I built the `dr-region` site, but didn't encounter this issue.

**Comment by laflessn** [comment]
Yes, dr-secure is built from a “transition” branch we created from the master branch in dr-region. DR only has regional planning, and the region.json is set for language = es. You can see the full error vis the console here https://maps2.coastalresilience.org/dr-secure/ 
Please advise.
