### ISSUE TITLE
Plugin scrollbar disappears iPad rotation from landscape to portrait and back

### ISSUE THREAD

**Issue by jwalgran** [CoastalResilienceNetwork/GeositeFramework#145]
Build 487
1. Orient the iPad in landscape view
2. Load the site
3. Rotate to portrait. scrollbar disappears because all plugins are onscreen.
4. Rotate to landscape

Expected: Scrollbar reappears
Actual: Plugin list is unscrollable.

**Comment by caseycesari** [comment]
Closing. Relevant to old version of framework.
