### ISSUE TITLE
Provide local failovers for all CDN assets

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#275]
If the CDN version fails to load, we should include a local resource.  We may also want to utilize the TNC AWS CloudFront CDN that is available to us rather than the 3rd party CDNs we currently use.

**Comment by caseycesari** [comment]
A lot of libraries are now sourced locally. However, many libraries are included in the ESRI JS API bundle, which has to be served from ESRI.
