### ISSUE TITLE
Particular WMS service blows up Layer Selector

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#277]
Data Type:          WMS Service
WMS Server:      http://gaia.inegi.org.mx/NLB/mdm5.wms?
Service Name:   Acervo de informacion geografica INEGI (Mapa Digital de Mexico)

Adding this to the config and selecting it will remove all the UI of the layer selector.

**Comment by caseycesari** [comment]
Closing. Relevant to old version of layer selector.
