### ISSUE TITLE
2 Plugin windows active at once

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#288]
You can make a situation where 2 plugin windows are active at once.

1. On a fresh page load, open the Layer Selector plugin
2. Drag the window slightly to the side
3. Click any other plugin
4. Both plugin windows are open

This only happens when you open Layer Selector first (or maybe, the first plugin in the collection?).  Once you close and reopen the plugin, the behavior returns to normal.  If you open another plugin first (even a Layer Selector based plugin), the behavior is correct.

I think this is an issue with the ``select`` [link](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/lib/backbone.picky.js#L125) method of backbone.picky.  It appears the event is not available right away, and it throws and suppresses an exception which prevents the following line of code from getting executed:

```js 
this.collection.select(this);
``` 
[link](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/lib/backbone.picky.js#L128)

 leaving the collection thinking that no items in the collection are selected.

This issue seems like it's been around a while.

**Comment by mmcfarland** [comment]
Verified that this affects whatever happens to be the first plugin in the sidebar, not Layer Selector specific.

**Comment by mmcfarland** [comment]
This comment seems to indicate that there is an alternative to to using the `select()` method:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/d2f18e2ff34490d2eeedd9813adac9ee3a6129e1/src/GeositeFramework/js/PluginBase.js#L35

**Comment by caseypt** [comment]
If you remove all of the bad layers from the layer selector, this behavior doesn't happen.

**Comment by caseypt** [comment]
I think the basic problem is that the Layer Selector plug-in `initialize` function [doesn't finish](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/main.js#L68) until all of the layers are retrieved or the requests time out. Once the initialization is complete, the behavior of the plug-ins is correct.

**Comment by mmcfarland** [comment]
Interesting.  I'm working on #320 which is going to reuse the `intialize` function, and found that removing the bad layers also allows my code for that feature to work.

**Comment by mmcfarland** [comment]
@caseypt FYI, WIP branch for #320 referenced above is pushed to my fork https://github.com/mmcfarland/GeositeFramework/tree/topic/layer-selection-use-regions

**Comment by caseypt** [comment]
I'm still trying to figure out what in [this callback](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/main.js#L69-L74) makes the layer selector behave normally.

**Comment by caseypt** [comment]
Commenting out [this line](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/ui.js#L38) keeps the layer selector open when another plug-in is activated, even if all the layer loading is complete. Not sure why that is yet.
