### ISSUE TITLE
Expose raw permalink has to admin users

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#291]
On the Save 'n Share dialog, a user should be able to expose the encoded URL (not shortened) so that they can copy it when creating "Launchpad Issues"

**Comment by caseypt** [comment]
@mmcfarland Can you clarify what you mean by admin users? Do we want to allow anyone to access the URL?

**Comment by mmcfarland** [comment]
Yeah, since we have no user system, yeah - anyone should be able to.  Sorry for the confusing language.  I'm picturing some expandable section on that panel that has the URL or maybe even just the fragment we'll need.

**Comment by caseypt** [comment]
Thanks! Great. That's what I implemented.

**Comment by caseypt** [comment]
Implemented in #296
