### ISSUE TITLE
Add toggle button for show/hide subregion polygons

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#294]
* Polygons should be togglable via a sidebar plugin (as per wireframes). 
* Add config setting to specify if polygons should be shown or hidden by default.

**Comment by caseypt** [comment]
Icon: 
![](smb://fileshare/projects/TNC_CoastalResilience/documents/design/icons/__new/map-layers/icon_sub_region.png)
