### ISSUE TITLE
Hide non-available plugins for subregion

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#300]
When entering a subregion, hide plugins which are not "available" to that subregion.  Availability should be determined by a new property in the subregion section of the region.json config.  Default to showing all plugins if that property doesn't exist.  Launchpad "issues" should also respect this when they also contain a subregion as part of the saved state.

**Comment by caseypt** [comment]
Implemented in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/307
