### ISSUE TITLE
Region polygon toggle plugin errors when no subregions are defined.

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#302]
If regions don't specify a subregion section in their region.json config, this line throws an undefined error:  https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/subregion_toggle/main.js#L14

I think the better check would be to prevent that plugin loading if there are no subregions in the config, though this will be a little extra work since it's a generic plugin and not explicitly tied into the framework subregion code.

**Comment by caseypt** [comment]
Shoot. Didn't consider that a config would load the plug-in but not have any subregions.
