### ISSUE TITLE
Launchpad: Layer selector plugin needs to load

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#314]
Currently, if a scenario is launched from the LP prior to the layer selector loading its layers, it throws an error.

**Comment by caseypt** [comment]
@mmcfarland Not seeing this behavior. Want to double-check on `master`?

**Comment by mmcfarland** [comment]
@caseypt I'm getting layer selector errors on master when selecting Flower scenario.  Do you not see that?

**Comment by caseypt** [comment]
I get the usual errors from layer selector, as well as this one:

![screen shot 2015-03-09 at 8 08 38 pm](https://cloud.githubusercontent.com/assets/1042475/6567067/2ce41e18-c698-11e4-84cb-6f0c60761b26.png)

However, I get that error when I try to open the layer selector in [production](http://maps.coastalresilience.org/us/) before it's done loading. Also, it doesn't prevent the "Multi-Hazard Mortality Risk Index" layer from being added on the map and eventually being selected in the layer selector once the plugin fully loads.

**Comment by mmcfarland** [comment]
@caseypt Nope, not seeing the described behavior in most recent `master`

**Comment by caseypt** [comment]
Okay cool. There is definitely a bug with the layer selector plug-in, but I'm pretty certain it doesn't have to do with the launchpad. Close this and reopen once we have time to diagnose the other bug?

**Comment by kdeloach** [comment]
@caseypt Not seeing this error anymore on latest master. Close?

**Comment by caseypt** [comment]
Yeah.
