### ISSUE TITLE
Launchpad: Set subregions based on saved state

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#315]
The launchpad scenarios may not respect the saved state for sub-regions.

**Comment by mmcfarland** [comment]
Additionally, just encoding a subregion in saved state will produce an error:
http://goo.gl/wFZVqf

I believe this worked initially, so is probably a regression.

**Comment by caseypt** [comment]
Commenting out [this line](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Pane.js#L186) allows a saved state with subregions to load without errors.

**Comment by mmcfarland** [comment]
@caseypt thanks! :bow:

**Comment by caseypt** [comment]
Though, that assumes there are no active plug-ins. If the layer selector is active on a map, errors are thrown. You then need to also comment out [this line](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Pane.js#L182).
