### ISSUE TITLE
Layer Selector doesn't update UI on savedState

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#334]
If a saved state contains layers active in the layer selector, they are shown on the map but the UI does not reflect the state with the appropriate checkboxes checked.

**Comment by mmcfarland** [comment]
This may not be an issue anymore, appears to be working in #330

**Comment by caseypt** [comment]
Confirmed. This appears to be fixed. Nice work. Closing.

**Comment by caseypt** [comment]
Reopening this. The UI is updated if you launch a saved state while the layer selector is still loading. If you wait until the layer selector is done loading, the UI is not updated.

**Comment by caseypt** [comment]
Also, if you remove all of the bad layers from the demo layer selector config, the UI is never updated with the active layers, even if you open it before it's done loading.
