### ISSUE TITLE
Fix the layer selector

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#354]
Tasks:

  - [ ] Render tree roots (disabled) before data is loaded
  - [ ] Indication in the UI if there was an error loading layers

**Comment by caseypt** [comment]
I think the basic approach here is to capture errors thrown by invalid layers. 

In the demo setup, there are a few different type of errors being thrown:

- Timeout errors from ArcGIS servers
- 404 redirect errors from the NOAA endpoints
- 'Access-Control-Allow-Origin' header errors from the marine services

In theory this should all be getting [caught](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/agsLoader.js#L194). But you never see this message, and a bunch of exceptions get thrown.

In this simple [example](http://developers.arcgis.com/javascript/samples/data_requestXML/) of `esri.request`, if you change the URL that it tries to retrieve to a bad URL, you'll see the same problem we are experiencing. Their error handler isn't actually called

**Comment by caseypt** [comment]
Another thing that might be helpful is to separate the drawing of the layer selector from the fetching. As it is now, the layer selector waits to draw the tree until all the layers are retrieved. Maybe it could draw the tree first, then gray out layers that fail. This might make restoring the state of the layer selector easier.

**Comment by kdeloach** [comment]
I updated the description with 3 tasks that should complete this issue.

**Comment by caseypt** [comment]
Kevin rightly pointed out that the errors are being caught. The messages are rendered to a little exclamation point icon in the layer selector. When you click that,  you see the caught error message.

Also, the esri example isn't working because there is an error in their error handler, not because the error handler isn't being called.

**Comment by kdeloach** [comment]
I spent some time on this and came to the conclusion that it would be very difficult to make these changes without doing a major refactor of the layer selector plugin. Closing for now.
