### ISSUE TITLE
Can't select text on map legend

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#372]
Mouse drag on map legend pans the map instead of selecting text.

**Comment by mmcfarland** [comment]
Also, cannot move/drag the legend in this scenario.  Seems to happen after a Scenario has been activated from the Launchpad.

**Comment by mmcfarland** [comment]
@caseypt This may need the same fix you gave to the map plugins z-index.  Can't find that commit, can you reference here?

**Comment by caseypt** [comment]
https://github.com/CoastalResilienceNetwork/GeositeFramework/commit/5edc835be6f210437983a197cb5d4332360cc7b7
