### ISSUE TITLE
Clear All adds checkboxes next to root node

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#399]
When the layer selector loads initially, there are no checkboxes on the root folder nodes. Pressing the "Clear All" link collapses the tree and adds checkboxes on the root nodes.

![image](https://cloud.githubusercontent.com/assets/43062/6900130/7fa7968a-d6d2-11e4-8808-0bf2daba3558.png)

**Comment by mmcfarland** [comment]
Closing due to rewrite.
