### ISSUE TITLE
Check layer selector custom subregion layer support

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#406]
Does not appear to be working as of a few days ago. May be related to layers being unavailable.

**Comment by mmcfarland** [comment]
After resolving the unavailable layers by updating the layers.json from gulfmex, some additional bugs are found:

* Scenario codes work as permalinks but not when launched from the Launch Pad
* Regions are not activated when part of a scenario, whether by permalink or Launch Pad
