### ISSUE TITLE
Metadata links don't work in subregion

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#420]
From Laura Flessner (6/2/15):

> Links to metadata or external sources within the blue info icons for a dataset don’t work when you’re within a region.  For example, in NC http://dev.maps.coastalresilience.org/northcarolina/     if “explore the map” is chosen from the Launchpad > open community planning app > expand Roanoke island folder > click blue icon next to Potential Wetlands (3rd layer down) > this link works fine.  However, if you select the “Roanoke island region” from the launch pad and perform the same steps, the link is no longer live.  I tested other geographies both on dev and production and this is also the case.

**Comment by laflessn** [comment]
Further, it looks like nothing that pops up in a window outside of the app interface works.  The opacity sliders don't work via the orange i buttons if clicked within a region .... it mouse pointer doesn't recognize the pop up window and simply shifts the base map beneath it.

**Comment by mmcfarland** [comment]
This looks like maybe a z-index issue when in SubRegion mode.
