### ISSUE TITLE
Print Task Instructions do not seem to work

### ISSUE THREAD

**Issue by mapossum** [CoastalResilienceNetwork/GeositeFramework#421]
On this page:

https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Export-Options

TNC requested some additional templates.  Following the instructions for adding templates did not work.  Specifically, the templates were added to the directory in the terminal server and the print task restarted.  The workaround that did end up working was to create a new print task and point the app to that one.  However it would be better to use the single print task rather than create a new one for each template.

**Comment by mmcfarland** [comment]
Export has been re-written to use browser based CSS media print.
