### ISSUE TITLE
pdf export map resolution

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#422]
the resolution of the pdf export maps is very blurry when compared to the dataset displayed in the mapping portal

**Comment by mmcfarland** [comment]
It looks like there is a `dpi` option for export settings https://developers.arcgis.com/javascript/jsapi/printtemplate.html#exportoptions

This could be explored for any dynamic map layers, but cached tiled maps would still use the pre-rendered tile.   Looks like the `dpi` default is `96`.

**Comment by mmcfarland** [comment]
The print is now based on the browser tiles and no longer being exported as PDF from the print service.
