### ISSUE TITLE
Remove EXTJS in layer rewrite or get it onto another faster CDN

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#460]
ExtJS is a large dependency and a bit difficult to work with. If possible, when rewriting the layer selector, we should avoid using it. If we need to use, try and create a custom version of it that does not include unused modules, or one that can be served faster than the current version.

**Comment by mmcfarland** [comment]
New layer selector is not designed to work with EXT Tree.
