### ISSUE TITLE
Reduce calls to layer server endpoints in Layer Selector load

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#462]
In the layer selector rewrite, we should aim to build out control with as few requests to map services as possible. Currently, when the layer selector is initialized, every map service is queried to see if it's active and to get some additional information. We should only query the map service for a layer when that particular layer is turned on. This might mean storing more information in the config file so that the control can be built with as few queries as possible.

**Comment by mmcfarland** [comment]
This was a placeholder issuer, closing in favor of actual implementation issues.
