### ISSUE TITLE
Develop new layer selector configuration schema

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#463]
Must include support for:

* Single Service architecture
* Ability to combine multiple layers of multiple services into a single "pseudo-service"
* Try not to rely on the index id as a sublayer specification
* Reduce startup requests

**Comment by mmcfarland** [comment]
Retain features like:

* Download Data links
* Opacity
* MetaData?
* Extent Zoom
* Filter
* Loading Saved State / Subregion state

**Comment by caseypt** [comment]
The initial draft of a new layer selector config schema can be found here, along with some notes and questions: https://gist.github.com/caseypt/afb0d266f3144af212d0

**Comment by kdeloach** [comment]
Added a few comments to that gist.

**Comment by caseypt** [comment]
We should discuss @kdeloach's comments before we start to on development for this.
