### ISSUE TITLE
Update Legend behavior

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#483]
From TNC

- Easily prepend a div to the existing legend.
- Make the legend div update it’s size dynamically to some agreed-upon min/max height/width.
- Ensure ordering of legend items as they correspond to active layers (sometime new legend items from plugins get added below existing items, other times they get added above – this even happens within layer selector - we need consistent rules for how items get added across plugins)

**Comment by kdeloach** [comment]
> Easily prepend a div to the existing legend.

Right now the legend displays visible map layers. Does this mean that plugins will be able to add arbitrary data to the legend?

> Ensure ordering of legend items as they correspond to active layers

The ESRI map has no knowledge of the order that layers appear in the layer selector. Since layers can be configured to appear out-of-order, we can't rely on service IDs or names to sort these correctly in the legend.

**Comment by kdeloach** [comment]
I recommend that we create some kind of data structure that contains a flat list of active layers, and the correct layer sort order. This data structure will be used to render the legend. All plugins will have access to this mechanism and are responsible for maintaining correct sort order.

We should keep this in mind as we make changes to the layer selector.

**Comment by mmcfarland** [comment]
> Does this mean that plugins will be able to add arbitrary data to the legend?

Yes, currently each plugin gets a reference to a "legend container" into which they can add arbitrary elements.

**Comment by mmcfarland** [comment]
Closing in favor of the referenced superseded issues.
