### ISSUE TITLE
Ensure ordering of legend items correspond to active layers

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#495]
> Ensure ordering of legend items as they correspond to active layers (sometime new legend items from plugins get added below existing items, other times they get added above – this even happens within layer selector - we need consistent rules for how items get added across plugins)

Ref: #483

**Comment by mmcfarland** [comment]
The preferred behavior would be for the most recently added layer to be on the top of the legend, which should also correspond to the z-index of the layer.

**Comment by kdeloach** [comment]
Can we wait on adding this until layer selector v2 is complete?

**Comment by mmcfarland** [comment]
@kdeloach Sure

**Comment by caseypt** [comment]
This seems to be somewhat tough to do without #559.
