### ISSUE TITLE
Export page broken

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#500]
Seems when we created the in-plugin print function that calls the brower's print, it broke the Generate Map within Export page

**Comment by mapossum** [comment]
The error I am getting makes it look like an error with the ArcGIS Javascript version like the error that was reported in the measure tool:

TypeError: esri.tasks.PrintParameters is not a function(…) "TypeError: esri.tasks.PrintParameters is not a function
