### ISSUE TITLE
Jumping legend

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#502]
in NYadaptation-region, Habitat Explorer plugin we get a jumping legend while in split view. This is happen when you choose forests as the habitat type.

**Comment by zferdana** [comment]
Jumping legend in Future Habitat also appears in Virginia-region when interacting with Flood plugin

**Comment by mapossum** [comment]
The jumping legend issue appears to be in many of the plugins such as Future Habitat when the plugin creates it's own legend.  Basically when one of these plugins are open and the map layers plugin is open you see it refreshing constantly.  Virginia is a good test case.  Open Future Habitat, then open map layers and turn on a few layers to see the issue.
