### ISSUE TITLE
Intermittent basemap appearing when initially launching a site

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#503]
Going to a site initially, whether in a cached browser or incognito, there is inconsistent behavior whether the basemap appears or is greyed-out

**Comment by mmcfarland** [comment]
@zferdana is this happening on sites besides Louisiana?  If so, can you add a comment about which regions?

**Comment by zferdana** [comment]
Yes, this is happening in New Jersey and NY Adaptation as well
