### ISSUE TITLE
Zoom to limits

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#505]
on maps.oceanwealth.org - map layers, Caribbean coastal vulnerability - zoom to does not work. is this a projection or function issue?

**Comment by mmcfarland** [comment]
The service should define `fullExtent` which the [layer selector uses](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/8bc450d242720c14e1a157d4cfe40ebd9c03bdc0/src/GeositeFramework/plugins/layer_selector/agsLoader.js#L250) to zoom to.  This service does define full extent.  It may be the coordinates or the extent itself is malformed.

http://services.coastalresilience.org/arcgis/rest/services/OceanWealth/Ocean_Wealth/MapServer?f=json
