### ISSUE TITLE
Test Legend (v2) against raster color ramp plugins

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#510]
In http://maps.coastalresilience.org/gsvg/ , check that the output as configured below, but the legend should have 3 ( I think ) ramp items, not two.  

![screenshot 2016-01-20 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/1014341/12463868/0e4a7da8-bf94-11e5-95cc-56eba4710ad2.png)

The missing, middle item has no label or value, which is probably why the ESRI dijit fails to render it. I'm hoping that our JSON approach will pick up all the breaks.

http://services.coastalresilience.org/arcgis/rest/services/GSVG/GSVG_Flood_and_SLR_Data/MapServer/legend?f=json

**Comment by ajrobbins** [comment]
Looks like this is now working as desired:
![screen shot 2016-06-22 at 5 15 49 pm](https://cloud.githubusercontent.com/assets/12868342/16283951/090846d6-389d-11e6-9ac6-c12240adc65c.png)

**Comment by ajrobbins** [comment]
@mmcfarland Are there any other raster color ramp plugins I could test?

**Comment by ajrobbins** [comment]
Tested with other raster color ramps and they look good, I think this issue can be closed:
![screen shot 2016-06-23 at 10 30 15 am](https://cloud.githubusercontent.com/assets/12868342/16306961/8ac7038e-392d-11e6-98a5-68414788b923.png)

![screen shot 2016-06-23 at 10 27 51 am](https://cloud.githubusercontent.com/assets/12868342/16306879/3e7f720e-392d-11e6-9917-914f6c908e60.png)

**Comment by caseycesari** [comment]
Closing based on the recommendation above.
