### ISSUE TITLE
Measure Plugin throws on `esri.UNITS.esriMile`

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#515]
Occasionally when loading the measure plugin, the `esri.UNITS.esriMile` property is undefined (to be specific, `esri.UNITS` is undefined).   This throws an exception which is now suppressed by the framework, but I didn't figure out why that field is sometimes unavailable.   I'm assuming it's related to the new JSAPI version and/or the bundle script.

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/measure/AgsMeasure.js#L57

**Comment by caseypt** [comment]
A potential solution may be to load the `esri/units` module and use that instead of the global `esri` object. That pattern is considered "legacy" and is deprecated. We should probably switch the uses of `esri.symbol.*` over as well.

https://blogs.esri.com/esri/arcgis/2013/10/14/the-abcs-of-amd/
