### ISSUE TITLE
Framework missing jQuery library and fails to load properly (unitedstates)

### ISSUE THREAD

**Issue by barrynickel** [CoastalResilienceNetwork/GeositeFramework#536]
An attempt to load a library (jquery.mCustomScrollbar.min.js) from js/lib fails due to a difference in name with the js file actually stored (jquery.mCustomScrollbar.concat.min.js) causing the application to not load at run time (corresponding css also fails).  Refer to http://maps.coastalresilience.org/unitedstates for an example of the issue.

NetworkError: 404 Not Found - http://maps.coastalresilience.org/unitedstates/css/jquery.mCustomScrollbar.css
NetworkError: 404 Not Found - http://maps.coastalresilience.org/unitedstates/js/lib/jquery.mCustomScrollbar.min.js

Failure point in the framework code occurs at line 259, Pane.js:

TypeError (not a function): view.$('.side-nav.top').mCustomScrollbar({ ...

**Comment by mmcfarland** [comment]
@zferdana It looks like http://maps.coastalresilience.org/unitedstates/ is running an older version of the framework - does this need to be updated?

**Comment by zferdana** [comment]
I have tried deleting the master version of the repo and replacing it with the dev branch with loads, but no luck. I get the site to come up but there is no base map and all the apps are blank. Why would dev be fine and master, with the same files, no load correctly? The master layer selector json file may need to be updated since it serves tiled services, but the other plugins should load fine

**Comment by barrynickel** [comment]
Zach I just checked and it is still the same problem with the js file in 
question (unrelated to tiled services).

------------------------------------------------
Barry Nickel
Director, Center for Integrated Spatial Research
Department of Environmental Studies
University of California, Santa Cruz
office: ISB 479
direct: 831.459.2890
email: bnickel@ucsc.edu
web: http://spatial.cisr.ucsc.edu
------------------------------------------------

**Comment by mmcfarland** [comment]
@zferdana It looks like it's an issue with the `unitedstates-region` repo.  It has included it's own version of Index.cshtml which overwrites the version which is provided by the framework (essentially, any file in the region repo will win if there is a conflict with the framework).  You should remove index.cshtml from the region and rebuild and you should get the latest version.

https://github.com/CoastalResilienceNetwork/unitedstates-region/tree/master/Views/Home

**Comment by mmcfarland** [comment]
Fixed via https://github.com/CoastalResilienceNetwork/unitedstates-region/commit/b11a5c95ad670145a19574df6ce95eae229f1f16
