### ISSUE TITLE
Empty folder nodes should fetch child layers

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#546]
Map services are now only fetched when clicking on leaf nodes. We should also fetch the map service when clicking of a folder node that contains on-demand layers that have not yet been loaded (ex. Coastal Resilience/Demographics).

**Comment by caseypt** [comment]
Is this still applicable after #576?

**Comment by kdeloach** [comment]
Fixed by 52a58229f6e6fd408a9bf527a516492f6525b973
