### ISSUE TITLE
Display loading indicator on info popup

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#551]

**Comment by caseypt** [comment]
And zooming to extent.

**Comment by caseypt** [comment]
Consider using http://ricostacruz.com/nprogress/, and adding it under the layers selector header or the filter area.

**Comment by caseypt** [comment]
Moved back to the back log because there were no points assigned to this card, and all of the points for this sprint are accounted for.

**Comment by caseycesari** [comment]
Migrated to https://github.com/CoastalResilienceNetwork/regional-planning/issues/89
