### ISSUE TITLE
If a request for a map service times out, all subsequent attempts to load the layer fail

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#557]
I think this is because the response is cached.

It can be seen frequently by activating the NOAA layers added in #556.

**Comment by kdeloach** [comment]
We could add a UI element to show that the service failed to load, with some kind of retry button as well.

**Comment by caseypt** [comment]
In the first version of the layer selector, once a service failed, it unavailable until the page was refreshed (and then it was tried again). With #576 in, should we still add the retry button?

**Comment by kdeloach** [comment]
I think we should definitely have some kind of indication that a service timed out in the UI. Once that is in, adding a retry option should be as easy as clearing the ajax cache for a particular service.

**Comment by caseypt** [comment]
Yeah, and using it some more, interaction with the broken service in the layer selector should be disabled until the layer is successfully retrieved.

**Comment by caseycesari** [comment]
Migrated to https://github.com/CoastalResilienceNetwork/regional-planning/issues/90
