### ISSUE TITLE
Geocoder input is truncated

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#569]
Current `develop` and `master` branches have the input within the geocoder truncated, which isn't occurring on production deploys:

![tnc-geocoder](https://cloud.githubusercontent.com/assets/1014341/13114644/60436e60-d562-11e5-9a38-2d55eaf5b94c.PNG)

Production:
![tnc-geocoder-good](https://cloud.githubusercontent.com/assets/1014341/13114655/75edb9dc-d562-11e5-9922-788ff2b1a8c6.PNG)

**Comment by mmcfarland** [comment]
The input rules are coming from regions which have the Community Rating System plugin installed.

The css input rules are applied broadly and affect all the inputs on the page.
https://github.com/CoastalResilienceNetwork/community-rating-system/blob/master/css/main.css#L59-L62

@cschneebeck can you look at reducing the scope of the css to only target the inputs within that plugin?

**Comment by cschneebeck** [comment]
Thanks for the heads up. I just commented it out and rebuilt the region. I’m working on an updated version of the that won’t use that anyways.

Cheers,
Casey Schneebeck | GeoWeb Developer | 415-722-9768
The Nature Conservancy - North America Science





On Feb 17, 2016, at 8:55 AM, Matthew McFarland <notifications@github.com<mailto:notifications@github.com>> wrote:


The input rules are coming from regions which have the Community Rating System plugin installed.

The css input rules are applied broadly and affect all the inputs on the page.
https://github.com/CoastalResilienceNetwork/community-rating-system/blob/master/css/main.css#L59-L62

@cschneebeck<https://github.com/cschneebeck> can you look at reducing the scope of the css to only target the inputs within that plugin?

**Comment by mmcfarland** [comment]
Fixed via ac2da7168ed40404da8a7b6f3cf3dc68bdde1972
