### ISSUE TITLE
Scroll position it not preserved when layer selector is rendered

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#574]
When the layer info box is opened, the layer selector is rerendered so that the "i" icon can be updated. This has the effect of scrolling the layer selector back to the top. If the user had scrolled down, this position is lost.

To fix this, we could preserve the scroll position in the state, and set it on render.

See #571 for more information.

**Comment by caseypt** [comment]
I don't think this was fixed by a175b3b. Now the eye icon will stay highlighted even after the layer info box is closed. It will return to inactive when another layer is selected or another layer's info box is open.

Also, the layer icons no longer remain open when clicking the layer tools menu.

**Comment by ajrobbins** [comment]
@mmcfarland  Is this issue solved in https://github.com/mmcfarland/GeositeFramework/commit/2ab5016f2806a863152265506beaf3eb1d96f6a1?

**Comment by mmcfarland** [comment]
Yes it is.
