### ISSUE TITLE
When gathering service URLs to preload data, layer groups should excluded

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#582]
The URLs for the Hurricane Sandy layers are reported as the following when gathering URLs to preload data:

```
http://services.femadata.com/arcgis/rest/services/2012_Sandy/undefined/MapServer
http://services.femadata.com/arcgis/rest/services/2012_Sandy/SurgeBoundaries_Final_0214/MapServer
http://services.femadata.com/arcgis/rest/services/2012_Sandy/2012_Sandy/MapServer
```

The first URL is invalid. I believe this is happening because of the way this service is defined in the config. The service information is shared between the two layers, but the name is specified at a lower level. 

```json
    {
        "displayName": "Hurricane Sandy",
        "server": {
            "type": "ags",
            "layerType": "dynamic",
            "url": "http://services.femadata.com/arcgis/rest/services/2012_Sandy/"
        },
        "includeLayers": [
            {
                "server": {
                    "name": "SurgeBoundaries_Final_0214"
                },
                "name": "FINAL - High Resolution Storm Surge Extent",
                "displayName": "Final FEMA Surge Area - February 2013"
            },
            {
                "server": {
                    "name": "2012_Sandy"
                },
                "name": "Hurricane Sandy - County Impact Analysis (click county for summary)",
                "displayName": "Hurricane Sandy - County Impact Analysis"
            }
        ]
    },
```

**Comment by kdeloach** [comment]
Even without preloading, this is an issue that happens when you toggle any layer that doesn't contain a complete service description. I don't know an elegant way around this, besides having the layer return NullService if its server block doesn't contain both a url and a name.

**Comment by caseypt** [comment]
I see. Yeah, that is tough. For GeoServer services, there will most likely never be a `name` set since that concept only exists in AGS.
