### ISSUE TITLE
unable to create new custom print task

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#590]
Can you take a look and see why in http://dev.maps.naturalresourcenavigator.org/ it is unable to find my new print task template that should be in http://services.coastalresilience.org:6080/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task 

The new template prefix
"customPrintTemplatePrefix": "Letter ANSI A NRN”  in the same export web map templates as "customPrintTemplatePrefix": "Letter ANSI A GeoSiteFramework”

I have followed these instructions for making a new print task template
https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Export-Options

I notice that template "customPrintTemplatePrefix": "Letter ANSI A OW” points to a different place in the config
http://dev.services2.coastalresilience.org/arcgis/rest/services/OceanWealth/PrintingOW/GPServer/Export%20Web%20Map

Not sure that I set this up and wonder why there is a distinct GPServer service for this. Thanks.

**Comment by kdeloach** [comment]
"Letter ANSI A NRN" is not in the list of supported print templates:

> A3 Landscape, A3 Portrait, A4 Landscape, A4 Portrait, Letter ANSI A GeoSiteFramework Landscape Legend, Letter ANSI A GeoSiteFramework Landscape, Letter ANSI A GeoSiteFramework Portrait Legend, Letter ANSI A GeoSiteFramework Portrait, Letter ANSI A Landscape, Letter ANSI A Portrait, Tabloid ANSI B Landscape, Tabloid ANSI B Portrait, MAP_ONLY

I would try to restart the print task to flush the cache, if you haven't already.

You can reproduce this error by [submitting a print task](http://services.coastalresilience.org:6080/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/submitJob) with these options:

Web Map as JSON:
```json
{"mapOptions":{"showAttribution":false,"extent":{"xmin":-8978361.286401775,"ymin":5000701.097071422,"xmax":-8409058.29973381,"ymax":5557774.159213759,"spatialReference":{"wkid":102100,"latestWkid":3857}},"spatialReference":{"wkid":102100,"latestWkid":3857}},"operationalLayers":[{"id":"layer0","title":"layer0","opacity":1,"minScale":591657527.591555,"maxScale":70.5310735,"url":"http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer"},{"id":"graphicsLayer1","opacity":1,"minScale":0,"maxScale":0,"featureCollection":{"layers":[]}},{"id":"graphicsLayer2","opacity":1,"minScale":0,"maxScale":0,"featureCollection":{"layers":[]}}],"exportOptions":{"outputSize":[800,1100],"dpi":96},"layoutOptions":{"titleText":"Test","scaleBarOptions":{},"legendOptions":{"operationalLayers":[]}}}
```

Layout Template:
Letter ANSI A NRN Landscape

**Comment by zferdana** [comment]
Thanks Kevin - the "Letter ANSI A NRN" prefix has four associated mxds for portrait, etc. I tried flushing the templates again. Don't know what else I can do unless there is a publishing step I am missing outside of just placing the templates in the webmaptemplates directory.
https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Export-Options

**Comment by kdeloach** [comment]
It's possible that the templates were published in a way that does not coincide with the wiki instructions. I would try to walk through this tutorial for publishing services for print:
http://server.arcgis.com/en/server/latest/get-started/windows/tutorial-publishing-additional-services-for-printing.htm

Beyond that, it looks like the GeositeFramework is configured correctly and is working as designed.

**Comment by zferdana** [comment]
I followed these instructions to add a web map service in In ArcCatalog or the Catalog window in ArcMap, browse to Toolboxes > System Toolboxes > Server Tools > Printing. Didn't work - most of these instructions are geared for 10.4 and we are on 10.3.

**Comment by zferdana** [comment]
Looking into this further the mxds seem fine as I am taking examples from GeositeFramework and saving them as other custom print projects. I assume these map docs serve both our dev and production servers as I have restarted both printing utilities in both ArcServer Managers. The dev and prod Managers say there is one instance running with a max of two.I may be missing a step but it seems when I restart these printing services they should pick up new mxds created in that directory. Also still puzzled why "Letter ANSI A OW” generated a different path than GeositeFramework. Will ask George
http://dev.services2.coastalresilience.org/arcgis/rest/services/OceanWealth/PrintingOW/GPServer/Export%20Web%20Map
