### ISSUE TITLE
enlarged launchpad

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#593]
http://dev.maps.coastalresilience.org/connecticut/ showing an oversized launchpad. I had to hide the production site. Why is this region showing such a large launchpad?

**Comment by kdeloach** [comment]
It looks like there is a miscalculation in how the width is determined when there are so many items in the launchpad. One workaround may be to limit the number of configurations to 5 or 6 per row until this is fixed.

**Comment by zferdana** [comment]
I am now seeing other strange behavior on http://maps.coastalresilience.org/connecticut/. Subregion red bar vanishes when trying to get to different places in the menu, and most troubling is that all save & share bookmarks don't work. I know if plugins are updated we need to establish new links, but the fact that all bookmarks are now inoperable to me means some framework update has affected the launchpad's main functions

**Comment by mmcfarland** [comment]
This version of Launchpad has been replaced with a new design.
