### ISSUE TITLE
trouble renaming Map Layers

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#594]
I tried adding a main.js file in the connecticut-region to rename Map Layers to Regional Planning. This is what we do for Community Planning, but this broke the site. Below is the config syntax in the main.js

define([
    "dojo/_base/declare",
    "plugins/layer_selector/main",
    "dojo/text!./layers.json"],
    function (declare,
              LayerSelectorPlugin,
              layerSourcesJson) {
        return declare(LayerSelectorPlugin, {
            toolbarName: "Regional Planning",
            fullName: "Configure and control layers to be overlayed on the base map.",

            getLayersJson: function() {
                return layerSourcesJson;
            }
        });
    }
);

**Comment by kdeloach** [comment]
Are you replacing the contents of an existing file or adding a new file? What error message did you receive?

The best way I can think to rename the Map Layers plugin is to open `plugins/layer_selector/main.js` and replace this line:

```
            toolbarName: "Map Layers",
```

with

```
            toolbarName: "Regional Planning",
```

**Comment by zferdana** [comment]
Yes, that is exactly what I did: put main.js in the layer selector folder of the region repo, did the name change as you indicate, but the site breaks - only the top blue bar of the application shows. Removing main.js from the layer selector folder gets the site back. Strange since you can have a main.js in the community planning folder that relies on layer selector and change the name...

**Comment by kdeloach** [comment]
I think the difference is that the community planning plugin *inherits* from the layer selector. By replacing the contents of layer selector as described above, the layer selector plugin is now trying to *inherit from itself*, which is creating a self-referential cycle.

To do what you're trying to accomplish, you would need to copy the original layer selector plugin into your region (https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/main.js#L52).

**Comment by zferdana** [comment]
This worked Kevin, thanks. For layer selector v2 I would officially change the name from Map Layers to Regional Planning with the new plugin icons in the GeositeFramework repo. That way folks don't have to copy the entire layer selector contents out of the Framework and into a region repo just to change the name when they should all be the same name across all regions. Thanks again.

**Comment by kdeloach** [comment]
Will do!
