### ISSUE TITLE
Move layer selector logic to core

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#595]
Or find a better way to customize existing plugin attributes.

Ref #594

**Comment by caseypt** [comment]
Since the new layer selector was moved to it's own repo and this issue applies to all plugins, I'm going to remove the `layer-selector-v2` label.

**Comment by kdeloach** [comment]
Fixed by https://github.com/CoastalResilienceNetwork/regional-planning/pull/19
