### ISSUE TITLE
 Rename "Map Layers" plugin to "Regional Planning"

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#596]
From #594:

> For layer selector v2 I would officially change the name from Map Layers to Regional Planning with the new plugin icons in the GeositeFramework repo. That way folks don't have to copy the entire layer selector contents out of the Framework and into a region repo just to change the name when they should all be the same name across all regions.

**Comment by caseypt** [comment]
Implemented in https://github.com/CoastalResilienceNetwork/regional-planning/pull/8
