### ISSUE TITLE
Extract LS2 to plugin

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#613]
The new layer selector can be included or not included like any other plugin.

**Comment by caseypt** [comment]
There's a way to move files from one git repo to another and to preserve the history of those files. I can't find the instructions I've followed before, but this looks like I simple method: http://stackoverflow.com/a/11426261/217378.

**Comment by caseypt** [comment]
I created https://github.com/caseypt/layer-selector-v2-test as a test using the following commands:

```
git clone git@github.com:CoastalResilienceNetwork/GeositeFramework.git test
cd test/
git fetch
git checkout layer-selector-v2
git remote rm origin # Just to make sure we don't mess with the source
git filter-branch --subdirectory-filter src/GeositeFramework/plugins/layer_selector_v2/ -- --all
git branch -m master
git remote add origin git@github.com:caseypt/layer-selector-v2-test.git
git push -u origin master
```

This produces a repo with only the files in `src/GeositeFramework/plugins/layer_selector_v2/` at the root of the folder with their history. The commits have new hashes, but there doesn't appear to be a way around that.
