### ISSUE TITLE
Info window positioned incorrectly

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#618]
The info window of the Layer Selector V2 renders itself inside of the plugin container.

![screenshot from 2016-03-29 10 42 47](https://cloud.githubusercontent.com/assets/1014341/14112106/656925b6-f59b-11e5-9305-ca5347fbaff1.png)

**Comment by kdeloach** [comment]
This may be fixed as part of some design changes that I'm making based on Jeff's feedback last week.

**Comment by caseypt** [comment]
This may not be an issue anymore:

![image](https://cloud.githubusercontent.com/assets/1042475/14316379/a237c5d4-fbd0-11e5-8783-8b92e2c67baa.png)

**Comment by mmcfarland** [comment]
Yep, this was fixed.

**Comment by kdeloach** [comment]
I thought putting `Fixes #618` in the commit description was supposed to automatically close the issue but I guess not...
