### ISSUE TITLE
i18n UnauthorizedAccessException

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#620]
I'm getting various permissions errors on the i18n files and folders. May be more of a system configuration issue than a coding error.

Running VS debug server throws this error:
![image](https://cloud.githubusercontent.com/assets/43062/14117336/38c1f90e-f5b2-11e5-870f-0c20746f18d1.png)

The languages folder exists but is set to Read-only. It's impossible for me to change this (even as admin):
![image](https://cloud.githubusercontent.com/assets/43062/14117377/701801f0-f5b2-11e5-829b-c018a2439b6f.png)

Additionally, any exception that occurs while assembling language files will throws a runtime error and will not log the exception to the error log.

**Comment by mmcfarland** [comment]
I wonder if we could get past those issues and the one reported in #610 if we didn't write a region-language file but instead just kept it in memory.  I believe we do something like this for the parsed region.json file.  If it's going to re-create the file on `App_Start` anyway, the actual file on disk isn't doing much except cause permission issues.

**Comment by caseypt** [comment]
Yeah, this is probably what is causing #610.

**Comment by kdeloach** [comment]
I like that idea.
