### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#633]
TNC requested a favicon be added to the core framework.

Icon (renamed from `.ico` to `.png`) is here:
![favicon ico](https://cloud.githubusercontent.com/assets/1014341/14429803/f2066610-ffcc-11e5-9f1c-aabf0af278a4.png)

**Comment by zferdana** [comment]
Matt - George and I worked on this for the develop branch. We included the favicon in the src/images folder as well as updating index.cschtml in the src/views folder. When you merge internationalization into the master branch can you be sure to include these updates? Then I will close this issue. thx - Zach
