### ISSUE TITLE
Export page limitations

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#634]
Image services either don't appear in the export page (http://maps.coastalresilience.org/northcarolina  with restoration explorer) or only show on the map with no legend (http://maps.coastalresilience.org/gulfmex with future habitat). Is this an Esri limitation?

**Comment by laflessn** [comment]
Also, layer headings for raster datasets (that show up fine in the mapping portal legend), do show up in any exported map legend...only headings for vector show up. This is in all geographies (CR and MOW) dev and prod. 

Essentially, we need Export Page to be able to compile and export outputs from multiple apps (vector, raster AND image service based) onto a single formatted map with compiled legend. If ArcGIS print service is having an issue with raster based data, is there a more flexible print service we can use??

**Comment by mmcfarland** [comment]
This has been superseded by browser print feature.
