### ISSUE TITLE
Extract Map Layers from develop

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#639]
- Extract old Map Layers from framework develop branch and place in it's own new plugin repo called “Map Tree” 
- Keep old Map Layers in master framework until we have fully adopted regional planning. Some further clarification to come on this.

**Comment by mmcfarland** [comment]
The above is confirmed.  We'll extract Map Layers to Map Tree, but then leave the existing plugin in the core.  Once folks have updated their regions to include Map Tree, we'll delete it.  Just make sure we don't touch the code in plugin code in master.

**Comment by mmcfarland** [comment]
New `map-tree` repo exists here: https://github.com/CoastalResilienceNetwork/map-tree

Same code stays in core, but will be deleted at some point in the future; no new work to be done on the framework included version.

h/t to @caseypt for the swell instructions on preserving history while extracting, taken from https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/613
