### ISSUE TITLE
Move framework develop to master

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#644]
Once https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/637 is complete, move internationalization to master.

**Comment by mmcfarland** [comment]
Pre-req:  Update spanish translations from TNC

**Comment by mmcfarland** [comment]
Translations are updated, and we're waiting for 5/31 to "release" to `master` to allow TNC to have time to test things out.

**Comment by mmcfarland** [comment]
This is the card to handle the last bit of release which will be done after any last minute feedback.
