### ISSUE TITLE
Restore the layer selector eye icon 

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#645]
We removed the eye icon in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/625, because the blue dots/circles serve a similar role. However, we have received feedback that the blue dots/circles that indicate that a layer has been added are too subtle, and should be replaced by the eye icon. The icon should be black, and located where the circles/dots are (to the left of the layer name).

**Comment by caseycesari** [comment]
Migrated to https://github.com/CoastalResilienceNetwork/regional-planning/issues/93
