### ISSUE TITLE
Change info text font color

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#646]
The text color in the box when you click on the info button in the layer selector should be black, not grey. 
![screen shot 2016-04-27 at 4 37 16 pm](https://cloud.githubusercontent.com/assets/12868342/14867422/737469b0-0c96-11e6-80e1-86fb99d80634.png)

**Comment by mmcfarland** [comment]
Shares a point with  #644
