### ISSUE TITLE
Update wiki with available regional-planning parameters

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#655]
The wiki should define/explain what parameters are configurable in the new layer selector (regional planning), like opacity. Needs more details cc/ @mmcfarland

**Comment by kdeloach** [comment]
We should probably also move the Layer Selector wiki pages from GeositeFramework to the map-tree repo.

**Comment by mmcfarland** [comment]
The wiki needs configruation overview and options, such as `downloadURL`, how to override default settings, etc.
