### ISSUE TITLE
Drag-handle overlap with scroll bar

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/GeositeFramework#674]
When a window (ie plugin) calls the scroll bar, he scroll bar down-button overlaps the drag-handle making it difficult to resize the window or scroll down using the button

![image](https://cloud.githubusercontent.com/assets/11575490/18597238/ecda23b4-7c01-11e6-8a99-1655173def48.png)

**Comment by mmcfarland** [comment]
Plugins are no longer resizable, but docked against the sidebar.
