### ISSUE TITLE
Spanish implemented in plugin

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#676]
We are close to successfully implementing the locales, Spanish version of Natural Coastal Protection plugin in dev MAR - https://goo.gl/tQ9MST - but the formatting is off. Our app developer thinks this is coming from the framework.

**Comment by caseypt** [comment]
Hi @lesserj. I was able to fix the encoding issue by switching out the invalid characters with valid characters from the site linked by @mmcfarland above.

![image](https://cloud.githubusercontent.com/assets/1042475/18883928/3fe9ffc0-84b3-11e6-9d4c-b39d7b3bf4e8.png)

I attached the "corrected" translation file as a sample (just drop the .txt from the filename). **Note** that the translations are not guaranteed to be correct. I swapped the invalid for valid characters without always knowing the correct spelling. I'm only attaching the file as an example.
[es.json.txt](https://github.com/CoastalResilienceNetwork/GeositeFramework/files/496208/es.json.txt)

**Comment by lesserj** [comment]
@mmcfarland Thanks.  That is strange.  I copied and pasted the correct characters from that site as well and it didn't make a difference.  I'll have to explore a bit to see what happened.  @zferdana I wonder why the accented characters from our translator came back invalid?  If we do a lot of translation files, we may want to come up with a way to validate the content so we don't miss an invalid character somewhere.

**Comment by kdeloach** [comment]
The character encoding used in the locale file must match the encoding that IIS uses to serve content, which should be UTF-8. The original locale file is encoded using **ISO 8859-1 (Latin-1)**.

You can also see this character encoding mismatch by viewing the raw file contents on GitHub:
https://raw.githubusercontent.com/CoastalResilienceNetwork/mar-region/830bbee713c42aa2d403f0b914dbb743fcde044a/plugins/mar/locales/es.json
