### ISSUE TITLE
no information visible on identify

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#678]
on http://dev.maps.naturalresourcenavigator.org open regional planning and make streams visible. We can't get identify to work on stream reaches. This is the tolerance question we had that may have never gotten addressed.

I also see a pull request from George that needs to be addressed. - thanks Zach

**Comment by mmcfarland** [comment]
@zferdana I fixed the stream identification issue in: https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/672 which was merged in on Sept 19th.  Can you verify that it's happening still on a recent dev install?

**Comment by mmcfarland** [comment]
Fixed in #672 and confirmed via https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/672#issuecomment-251140639
