### ISSUE TITLE
Plugin initial position not offset by subregion toolbar

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#681]
Initial position for plugins should be slightly below the geocoder plugin:

![image](https://cloud.githubusercontent.com/assets/43062/19043470/48c9242c-895e-11e6-836f-935b6c095f01.png)

However, if the subregion toolbar is visible then plugins will open on top of the geocoder plugin, clipping it:

![image](https://cloud.githubusercontent.com/assets/43062/19043478/4f9dd022-895e-11e6-9be0-5991e493cd3e.png)

**Comment by mmcfarland** [comment]
Floating windows have been removed in favor of a docked sidebar.
