### ISSUE TITLE
Wire up new UI prototype (0 pts)

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#683]
Originally 12 pts

**Comment by caseypt** [comment]
-3 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/684

**Comment by caseypt** [comment]
-1 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/689
-2 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/688
-2 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/686
-1 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/692
-2 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/691

**Comment by caseypt** [comment]
+1 from https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/689

**Comment by caseypt** [comment]
-2 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/694
