### ISSUE TITLE
Add ellipse map control

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#688]
- Add ellipse map control
- Move measure and zoom to extent to ellipse control
- Convert print and save and share to map controls.

![image](https://cloud.githubusercontent.com/assets/1042475/19445124/0a8b56f4-9461-11e6-98f3-e0b49d837492.png)

**Comment by kdeloach** [comment]
Leaving 2 points on this from last sprint to complete #708 (the changes were more involved than I anticipated).
