### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#690]
~~Close button on map controls (like the search) is not circular. The search control close button is hard to click as well.~~ This was replaced by a new control.

**Add styles for "Get Started" button**

Currently:

![image](https://cloud.githubusercontent.com/assets/1042475/19487222/d355edd2-952f-11e6-8c00-c667585b6b82.png)

Should be:

![image](https://cloud.githubusercontent.com/assets/1042475/19487228/d9bc03f0-952f-11e6-84f1-83186ee7f086.png)

**Plugin header doesn't adjust to different plugin window sizes**
![image](https://cloud.githubusercontent.com/assets/1042475/19566845/aec12122-96b9-11e6-9534-8d2419e0799e.png)

**Plugin container padding cuts off plugin**
![image](https://cloud.githubusercontent.com/assets/1042475/19567010/46a0e5cc-96ba-11e6-92ba-1dbe23ce9bbc.png)

**Search control overlaps with region menu on small screens**
![image](https://cloud.githubusercontent.com/assets/1042475/19664460/71d086ce-9a0e-11e6-8f7b-8d6deee24a83.png)

**Export and save and share modals relied on Foundation, and needs to be reformatted**
![image](https://cloud.githubusercontent.com/assets/1042475/19732637/5ad3fe1c-9b6f-11e6-9c49-995196546db1.png)

**Comment by kdeloach** [comment]
Activating a subregion hides the "toggle subregion" map plugin. However, it leaves a large gap because we are only hiding the launcher button, instead of the entire plugin container.

![image](https://cloud.githubusercontent.com/assets/43062/19738503/b91e73ec-9b85-11e6-9168-eb50d8fb51d6.png)

**Comment by mmcfarland** [comment]
`<li>` elements retained their bullet style.  This can be seen on the "overflow map tool menu" and also the plugin list before the sidebar is fully rendered.

![screenshot 2016-11-03 at 9 15 07 am](https://cloud.githubusercontent.com/assets/1014341/19967542/24412d46-a1a7-11e6-960e-47f778830f1c.png)
