### ISSUE TITLE
Implement installation drop-down menu

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#692]
- This is currently hard-coded in the prototype. How should this list be configured?

![image](https://cloud.githubusercontent.com/assets/1042475/19445343/dd2837bc-9461-11e6-856d-90724117c01c.png)

**Comment by mmcfarland** [comment]
This is currently configured as a `headerLink`, we should probably reuse the parsing and config, but promote it from a generic link to a specific region list link.

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/region.json#L14-L20

**Comment by caseypt** [comment]
I think `headerLink` now represents this:

![image](https://cloud.githubusercontent.com/assets/1042475/19445974/a76d5938-9464-11e6-8162-548c66cdebf8.png)

So maybe add a `regionLink` list?

**Comment by mmcfarland** [comment]
Sorry, I meant that's how it's configured currently in the regions: https://github.com/CoastalResilienceNetwork/gulfmex-region/blob/master/region.json#L9-L21

I think we should pull it out from the generic `headerLink` to a specific `regionLink` as you suggest.

**Comment by caseypt** [comment]
Ah got it. Didn't notice it in the header before. Thanks.
