### ISSUE TITLE
Update basemap selector style

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#693]
Currently:

![image](https://cloud.githubusercontent.com/assets/1042475/19456403/43fe1240-948f-11e6-939f-1b024f05098c.png)

Should be:

![image](https://cloud.githubusercontent.com/assets/1042475/19456388/2e1f83be-948f-11e6-9a9b-8f7c3759f4ac.png)

May need input from @jfrankl on what it should look like when it's expanded.

**Comment by jfrankl** [comment]
I think this is fine as is.
