### ISSUE TITLE
Implement plugin layer hiding functionality

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#694]
Clicking the eye icon should hide any layers added by the plugin.

![image](https://cloud.githubusercontent.com/assets/1042475/19477411/01c77e8e-950c-11e6-829c-594947c66d8f.png)

**Comment by kellyi** [comment]
Per @jfrankl this button should toggle the layers off and make the corresponding changes to the legend, but it should leave the plugin open. That means it's not really either `.hibernate` or `.close`, exactly, so I'll rework what I did in #702 to handle toggling.
