### ISSUE TITLE
Fix map plugin activation

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#700]
Clicking on this plugin doesn't appear to be activating them.

**Comment by ajrobbins** [comment]
Closing in favor of https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/688

**Comment by kdeloach** [comment]
I'd like to reopen this issue because it's still happening for me and it doesn't seem caused by #688 (nor does it seem within the scope of #688 to fix).
