### ISSUE TITLE
Move search control to header

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#701]

**Comment by kellyi** [comment]
I hacked around with this by moving the DOM elements around in the HTML source of the page and adjusting some CSS rules and:

<img width="1197" alt="screen shot 2016-10-19 at 5 32 17 pm" src="https://cloud.githubusercontent.com/assets/4165523/19538462/200dca94-9622-11e6-913c-b2c6ba011e1d.png">

This control's currently implemented as a plugin. Do we have any existing plugins which occupy the navbar like this? If not, would we want to make it possible to add plugins to the header (at least this one) or should this just be set up as a non-plugin feature?

**Comment by kdeloach** [comment]
I think this should become integrated into the framework rather than exist as a plugin.

**Comment by caseypt** [comment]
Per @mmcfarland, I'm going to replace our search control with the built in ESRI search control (demo here: https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=search_basic). The search control will be baked into the framework and will no longer be a plugin.
