### ISSUE TITLE
Implement TNC UI feedback

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#704]
- Some regions may not want the region name dropdown to facilitate switching away from their region so easily. We should add a configuration option in which there is no region dropdown (need to figure out where other regions will live in header/navigation), and potentially one in which the dropdown has subregions.
- Plugin menu should collapse when plugin is selected, like it is on small screens/tablets. The active plugin icons should stay highlighted.
- Need to show which plugins are active - icon a different color? Vs which plugin is being shown in the sidebar - background highlighted?
- In the responsive design for tablets, the plugin menu is collapsed so only the icons are visible. The plugin name is shown in a tooltip on hover. How will this work with touch?
- ~~How to show that a plugin is activated but not visible (eye icon) in the plugin menu - currently, there's no way to see the eye icon/visibility status from the plugin menu~~
- ~~Need to figure out how the eye icon works - currently, when layers are turned on, it remains grey. It turns blue on hover, but when clicked it removes the layers from the map. This seems confusing. Need a way to have the eye icon show that layers are on the map, and figure out visual signal that it's showing layers off vs on~~

**Comment by kellyi** [comment]
eye-close icon to display when the layers are toggled off: 

http://fontawesome.io/3.2.1/icon/eye-close/

otherwise, show the eye-open icon

**Comment by caseypt** [comment]
> Some regions may not want the region name dropdown to facilitate switching away from their region so easily. We should add a configuration option in which there is no region dropdown (need to figure out where other regions will live in header/navigation), and potentially one in which the dropdown has subregions.

The region dropdown can be removed by not including the `regionLinks` object in `region.json`.

**Comment by mmcfarland** [comment]
> The region dropdown can be removed by not including the regionLinks object in region.json

I think the better behavior would be to still display the region label, just without the dropdown.

**Comment by mmcfarland** [comment]
These tasks have been broken out to other issues or completed.
