### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#706]
- Plugin sizing options
- Region installation menu config

**Comment by kellyi** [comment]
I updated "Plugin Settings" on the wiki to document the new `size` option (and change `width` and remove `height`) here: https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Plugin-Settings

I also updated the "Region.json Settings" page to document using the `regionLinks` array to configure that dropdown here: https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Region.json-Settings
