### ISSUE TITLE
Identify point remains disabled after deactivating a plugin with allowIdentifyWhenActive set to false

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#716]
Activating then deactivating a plugin with `allowIdentifyWhenActive` set to false, disables the identify popup, until another plugin with `allowIdentifyWhenActive` set to true has been activated.

I have only observed this behavior (so far) with the "measure" map plugin.
#### Steps to reproduce
- Load application
- Click map
- The identify popup appears (as expected)

![screenshot 2016-10-24 at 15 14 33](https://cloud.githubusercontent.com/assets/43062/19660681/c7124ba0-99fe-11e6-817a-d087dbd38fe2.png)
- Activate then deactivate the "measure" plugin:

![screenshot 2016-10-24 at 15 53 19](https://cloud.githubusercontent.com/assets/43062/19661522/13269868-9a02-11e6-9d85-8e4cb86cdfa7.png)
- Click map
##### Expect:
- Identify popup should appear
##### Actual:
- Nothing happens

Ref #715

**Comment by mmcfarland** [comment]
Resolved by #769
