### ISSUE TITLE
Replace nav icon hover effect with Bootstrap tooltip

### ISSUE THREAD

**Issue by jfrankl** [CoastalResilienceNetwork/GeositeFramework#728]
Currently, the hover effect on the sidebar nav buttons is defined in CSS (`.nav-apps-button:hover`).

We should use the Bootstrap tooltip component for this instead. This should work better.

![image](https://cloud.githubusercontent.com/assets/1809908/20140402/f26c366a-a658-11e6-9efe-9e9915c7b9be.png)

**Comment by mmcfarland** [comment]
Superseded by #818
