### ISSUE TITLE
Sidebar app icons

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#729]
A list of app icons that need to be converted to "new" style.  Ideally, the result of this is a directory of directories, which are named after the plugin, aka:

```
new_icons \
   regional-planning \
      icon_sm.png
   coastal-defense \
      icon_sm.png
``` 
(There may be some duplicates, I tried to remove)
https://github.com/CoastalResilienceNetwork/regional-planning/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/multiexplorer/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/future_habitat/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/coral-reef-fisheries/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/coastline-change/blob/development/icon.png
https://github.com/CoastalResilienceNetwork/community-rating-system/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/filterSelect/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/enba/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/flood-slr-ca/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/eca/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/map-tree/blob/develop/icon.png
https://github.com/CoastalResilienceNetwork/feature-compare/blob/master/icon.png
https://github.com/CoastalResilienceNetwork/waterflow/blob/master/icon.png

We can then just send TNC a zip of the files and have them update their new repositories.  Since the filename is new, we'll have the `prototype` branch code look for it while the `develop` code looks for the existing names.

@zferdana are you aware of any other images that would need to be converted to the "new" style?

**Comment by jfrankl** [comment]
Here are the icons.

[cr-icons.zip](https://github.com/CoastalResilienceNetwork/GeositeFramework/files/620389/cr-icons.zip)

**Comment by kdeloach** [comment]
After #746 is merged in we can have @zferdana update the other plugins. Just need to add each image to the respective plugin repo (ex. https://github.com/CoastalResilienceNetwork/regional-planning/pull/65).

**Comment by mmcfarland** [comment]
These have been developed and deployed.
