### ISSUE TITLE
Opening the map utils plugin closes open sidebar plugin

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#734]
I think the sidebar plugin should stay open.

To reproduce:
- Activate the regional planning plugin or another sidebar plugin.
- Click the map utils button.
- The regional planning plugin will close.

![image](https://cloud.githubusercontent.com/assets/1042475/20353998/b62bd998-abea-11e6-9701-740730f00ffe.png)

![image](https://cloud.githubusercontent.com/assets/1042475/20354003/ba3a600e-abea-11e6-8b7a-e3ffe7c2c56a.png)

**Comment by kdeloach** [comment]
This is actually by design. You can reproduce this behavior in production by opening any sidebar plugin and then activating the measure plugin.

**Comment by caseypt** [comment]
Ah, got it. We may want to change it so that it closes only if you select one of the map util plugins. Currently it closes the sidebar plugin even if you just click the map utils button to open the menu.

**Comment by kdeloach** [comment]
Yeah, I tried really hard to figure out a way to open that menu without "activating" the plugin but the API just isn't flexible enough to allow this. I thought setting the plugin option `closeOthersWhenActive` to true would do the trick but it had some negative side effects. Definitely agree the current behavior is counter intuitive.

**Comment by caseypt** [comment]
I spent a little bit of time looking into this, and I think @kdeloach is correct. There's not a good way to do this without some changes to the plugin API.
