### ISSUE TITLE
TNC feedback

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#737]
- Add external link icons to hamburger menu options
- Move tour to the bottom left of the plugin menu and rename to "Help"
![pasted image at 2016_11_16 02_09 pm](https://cloud.githubusercontent.com/assets/12868342/20365029/6ab7c34a-ac13-11e6-8f95-0feebf912687.png)
- Slim down plugin menu and sidebar

**Comment by mmcfarland** [comment]
@jfrankl is doing the slimming and creating a space in the sidebar for the tour link.

This task for us is to:
* Move the configuration for tour, which is currently an attribute for a `HeaderLink` and create a dedicated tour link as Help in the space @jfrankl created.
* In the overflow menu item, add the icon for external links

**Comment by jfrankl** [comment]
[Slimming Down with Jeff](http://www.cc.com/video-clips/dz4o0c/the-daily-show-with-jon-stewart-slimming-down-with-steve---nutrition)!

**Comment by caseypt** [comment]
Created https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/752 to address this.

I have a couple questions:

- There currently isn't much configuration for the tour:

```
{ "text": "Tour", "url": "javascript:;", "elementId": "help-overlay-start"}
```

This issue says to move the configuration for the tour, but do we need it at all?

- Do we want to support drop-down menus in the hamburger menu?

![image](https://cloud.githubusercontent.com/assets/1042475/20629342/03005cac-b2f9-11e6-913e-d2c3e6017f5d.png)

The “Menu” option doesn’t work right now, but I’m not sure if we want to support it.

**Comment by mmcfarland** [comment]
@caseypt 
1. no, we don't need that precise configuration, we should just have a dedicated link for tour in the new spot.
2. no, the only expectation is that there will be external links in that overflow menu.

**Comment by mmcfarland** [comment]
This is updated to include making the element to contain the `Help` button and converting the existing Tour trigger/config to just a dedicated link which triggers the behavior.
