### ISSUE TITLE
Work out print and preview sizing area

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#744]
Complete work on the print preview and the printable areas
* ~~Preview map size relating to print size~~
* Remove map print preview.  TNC would like to just use the browser print preview as the whole preview.  The center of the map should be preserved in the printed version, and screen map that is outside the container for print will will just be clipped.
* Legend and map formatting
* Landscape vs Portrait

**Comment by jtarricone** [comment]
To be clear, point 2 means undoing #735 right?

**Comment by mmcfarland** [comment]
Correct.  The map should be centered in the print element the same as the display element, meaning that the extent will be different for the two sizes.
