### ISSUE TITLE
Finish sidebar styling

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#755]
Apply additional styling around sidebar icons to reduce size.

![image](https://cloud.githubusercontent.com/assets/43062/20773347/547eccc4-b71f-11e6-8283-3897cb8f9af0.png)

Ref: https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/746#issuecomment-264011390

**Comment by mmcfarland** [comment]
In the same area, plugins that remain "active" have styles that bleed into each other a bit.  See screenshot in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/746#pullrequestreview-10897664.

**Comment by mmcfarland** [comment]
There was feedback relating to not visually knowing which plugin button was associated with the currently displayed window, despite it saying the active color.

**Comment by ajrobbins** [comment]
It appears that there's currently only an `active` class on the plugin button when it's open; we'll need to add another type of class for a plugin that's open but not active in the sidebar. Then @jfrankl can follow up and style it.
