### ISSUE TITLE
Feedback from prototype demo

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#756]
Implement fixes from prototype demo.

**Comment by ajrobbins** [comment]
Originally 3 points

**Comment by ajrobbins** [comment]
-1 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/755#issuecomment-265257911

**Comment by ajrobbins** [comment]
Some feedback: 
- Need to generate documentation for how to transition to using the new framework version as was done for https://github.com/CoastalResilienceNetwork/ny-prototype-region, including any changes in configuration processes.
- Extend documentation for custom legend implementation
@mmcfarland can provide details
