### ISSUE TITLE
UI issues on tablet

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#771]
#### Instructions
In the comments of this issue are a list of known problems with various tablets.  The first step would be to apply the output of the autoprefixer mentioned, to see what that resolves by itself.  The goal will be to check off as many of the items in this list as possible.

**Comment by kdeloach** [comment]
Verify that legend can be minimized with Safari on iPad.

**Comment by zferdana** [comment]
Legend can't be minimized on iPad in Safari confirmed

**Comment by jfrankl** [comment]
After some testing, I have found that autoprefixer will solve that initial "Browserstack with Chrome on iPad Air" issue, Arianna.

The issue seems to be that some Browserstack devices use older versions of browsers or operating systems. When you get back to iOS 8, our site breaks. If we use autoprefixer to support the last 3 versions, it works.

Before autoprefixer:

![image](https://cloud.githubusercontent.com/assets/1809908/21274360/cd58a2c8-c395-11e6-9bfd-eb0dfe30ffac.png)

After autoprefixer:

![image](https://cloud.githubusercontent.com/assets/1809908/21274371/e02d930e-c395-11e6-9f7c-1eee485acb3c.png)

**Comment by ajrobbins** [comment]
Good find, thanks @jfrankl !

**Comment by kdeloach** [comment]
I will try to identify which styles are generated from the CSS autoprefixer and apply them manually.

**Comment by kdeloach** [comment]
Jeff suggested using https://autoprefixer.github.io/ to add missing styles.

**Comment by kdeloach** [comment]
Here are the browsers we are targeting for this iteration:

* iPad 2
* iPad 3
* iPad Air
* iPad Air 2
* Nexus tablet (Safari, Chrome)

**Comment by ajrobbins** [comment]
Issues noted on iPad 3 running iOS 9.3.2, using Safari:
- [ ] Not seeing any layers in regional planning
- [ ] ... button icon is off-center. This may not matter with the new wrench icon, but I didn't see that on the ny-prototype.
![img_0091](https://cloud.githubusercontent.com/assets/12868342/21370985/b512e260-c6dc-11e6-890d-572029104451.jpg)

- [ ] Tooltip with app name on hover doesn't work with tablet; the tooltip hangs around, blocking the sidebar:
![img_0092](https://cloud.githubusercontent.com/assets/12868342/21370996/cf4ec0d6-c6dc-11e6-874e-6c067f11a16a.jpg)

- [ ] When I open the flood & sea level rise plugin, it squishes the header bar
![img_0093](https://cloud.githubusercontent.com/assets/12868342/21371015/e83ff358-c6dc-11e6-8afe-a1ffff56fd91.jpg)

- [ ] Tapping the basemap selector opens the basemap menu. Tapping it again does not close the menu. Can only collapse basemap dropdown menu by opening a plugin.

**Comment by ajrobbins** [comment]
With the latest on ny-prototype, I'm now seeing the wrench icon but it's off-center too:
![img_0098](https://cloud.githubusercontent.com/assets/12868342/21396988/10f65fce-c770-11e6-99ad-53c922034bf0.jpg)

**Comment by ajrobbins** [comment]
On Nexus tablet, running Chrome:
- [ ] the full page width doesn't show on initial load; the right side (including basemap selector and other buttons) is cut off)
![screenshot_2016-12-21-11-51-09](https://cloud.githubusercontent.com/assets/12868342/21398468/6a712c5a-c775-11e6-9c12-a40a643fd957.png)

- [ ] Physical basemap doesn't load
![screenshot_2016-12-21-11-51-54](https://cloud.githubusercontent.com/assets/12868342/21398496/833fd812-c775-11e6-8e18-18e615e8e2c7.png)

- [ ] Legend opens too far to the left by default, it's partially hidden by the sidebar
![screenshot_2016-12-21-11-54-23](https://cloud.githubusercontent.com/assets/12868342/21398510/8e9ee9be-c775-11e6-89e2-bb6511417af8.png)

- [ ] Can't collapse the basemap menu by tapping the top of the menu (same as iPad/Safari)
- [ ] hamburger menu opens behind sidebar
![screenshot_2016-12-21-11-56-44](https://cloud.githubusercontent.com/assets/12868342/21398521/9cae3fe6-c775-11e6-8efe-b9f30d7c6b9a.png)

Regional Planning plugin shows layers though, unlike on iPad/Safari

**Comment by kellyi** [comment]
- [ ] hamburger menu doesn't seem to open on iPad/Safari either

**Comment by kellyi** [comment]
re: Regional Planning layers: looks like that was due to something off in the plugin's css.

**Comment by kellyi** [comment]
re: "Tooltip with app name on hover doesn't work with tablet": I checked this in iOS Safari and the current behavior is that the tooltip appears until the viewport gets a tap somewhere outside the plugin buttons. Tapping on the map, the plugin sidebar, or anywhere that's not a plugin button causes it to disappear.

I think that's generally the desired/desirable behavior, although I think it may also be good to have the tooltip close if you tap the plugin button which is showing it. @jfrankl do you have any suggestions for this?

**Comment by kellyi** [comment]
An alternative solution would be to dismiss the tooltip if the plugin which generated it is currently not minimized, as the title makes the tooltip redundant anyway.

**Comment by jfrankl** [comment]
Here's what I'd like to see.

On page load, the full navigation is visible.
![screen shot 2016-12-23 at 11 55 16 am](https://cloud.githubusercontent.com/assets/1809908/21458736/ff8d6c6c-c906-11e6-8203-8d032df55bea.png)

When the sidebar is open, the text in the sidebar is hidden, reducing the size of the navigation.
![screen shot 2016-12-23 at 11 55 48 am](https://cloud.githubusercontent.com/assets/1809908/21458812/90c0eff6-c907-11e6-8c6f-ac847cda1188.png)

The tooltip behavior is eliminated. If the sidebar closes after being open, the full navigation is visible again.

**Comment by kellyi** [comment]
I'm updating how the plugin sidebar works on tablets in portrait mode in #818: we dispense with the tooltips altogether, and we show the full titles when no plugin content's visible and just the icons otherwise.

In landscape mode and on desktop (basically: on viewports > 991px wide), we keep the prior behavior, which didn't include the tooltips but did always show the full plugin titles.

**Comment by kellyi** [comment]
Wrench icon misplacement seems to be happening because the button's inheriting some CSS rules related to the font here: 

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/prototype/src/GeositeFramework/css/main.css#L314

I tried just removing that line but it impacted other buttons in the app, so I'll see if I can just cancel some of the inherited properties on the wrench button.

**Comment by kellyi** [comment]
re: "Physical" basemap: it seems to be working both on desktop and iPad Safari now, so I closed #810.

**Comment by kellyi** [comment]
Summarizing what's been done for this card:

- [ ] fix undefined function #798 
- [ ] make layers selectable in regional-planning https://github.com/CoastalResilienceNetwork/regional-planning/pull/69
- [ ] center wrench icon on iOS Safari #819
- [ ] replace tooltip behavior on narrow viewports #818 

Left to do:
- [ ] check app display on Nexus tablets

**Comment by kellyi** [comment]
I'm going to move the Nexus tablet issues to another card.
