### ISSUE TITLE
Add scale bar (feet and meters; miles and kilometers) to base maps

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#776]
> We need this added to the new framework. I wanted to flag this as a priority request even though this is in our amendment for work starting in January. It would be great to have this implemented in the next couple of weeks as we build training materials illustrating the new framework. Please comment if this is an issue to complete by the end of the calendar year.

Updated (@mmcfarland):
Add a scalebar widget to the framework, at the moment let's not have this a configured show/hide, but just show always.

https://developers.arcgis.com/javascript/3/jssamples/widget_scalebar.html

**Comment by mmcfarland** [comment]
@zferdana we can work this in very quickly.
