### ISSUE TITLE
Update legend initial position

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#778]
There's a gap between the initial legend position and the right side of the screen. Was this intentional?

![image](https://cloud.githubusercontent.com/assets/43062/21201669/d6eaec38-c219-11e6-963a-43bc48950eaa.png)

**Comment by ajrobbins** [comment]
I think this gap is ok on desktop, but becomes problematic on tablet as notes in https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/771#issuecomment-268577273

I think we should move it closer to the right side by default.

**Comment by mmcfarland** [comment]
Shares a point with #816
