### ISSUE TITLE
Scrollbars appear after closing modal dialogs in IE

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#779]
* Load page
* Open "Save & Share" (or any other modal)
* Close modal

![image](https://cloud.githubusercontent.com/assets/43062/21203483/9d1f1a54-c220-11e6-96bc-ae1d640ee2ad.png)

**Comment by mmcfarland** [comment]
Recent updates have fixed this, I can no longer replicate this behavior.
