### ISSUE TITLE
Smooth transition when closing plugins

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#780]
When the width of the map is adjusted to accommodate the space required or relinquished by toggling the state of a sidebar plugin, the map animates very abruptly, usually leaving a momentary black block along the right border.  The esri map controls also jump away from the fake map controls that aren't actually contained in the map div.

We should animate the width transition so this is a more visually appealing experience.

**Comment by kellyi** [comment]
I did a bit of investigation for this one and it looks like it's possible to use a keyframe animation to set `width: 0px` and `visibility: hidden`  to the plugin sidebar over a 500ms transition as it's hiding. However, it seemed like the underlying map didn't update anymore quickly when I made that change, and so it remained noticeable.
