### ISSUE TITLE
Final design fixes for UI update

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#783]
- [x] Add a border between active plugins
- [x] Style Tour button
- [x] Change ... icon to wrench
- [x] Add a border or shadow on the right edge of the sidebar

**Comment by ajrobbins** [comment]
- [ ] Launchpad touchups (font) from https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/748

**Comment by jfrankl** [comment]
I replaced "Style active class for plugins" with #792. Will need developer support on that.

**Comment by ajrobbins** [comment]
Looks good from the screenshot!

**Comment by mmcfarland** [comment]
These have all been implemented.
