### ISSUE TITLE
Update unit display for measure

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#784]
The measure tool offers display units in two spots, while the drawing is in progress:
![screenshot from 2016-12-15 11 23 18](https://cloud.githubusercontent.com/assets/1014341/21232209/e52f0596-c2b8-11e6-88c2-669743622419.png)

and after the measure is complete:
![screenshot from 2016-12-15 10 22 19](https://cloud.githubusercontent.com/assets/1014341/21231972/13d35c40-c2b8-11e6-81dc-cae72f62af90.png)

These should be updated to also include the appropriate metric unit as well

* miles/kilometers
* mi2/km2, 
* acres/hectares

**Comment by kdeloach** [comment]
Just double checking-- Do we want to replace imperial units with metric? Or display both?

**Comment by mmcfarland** [comment]
We'll display both.
