### ISSUE TITLE
Update tour elements

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#786]
The tour looks pretty good considering the UI changes, a few follow up tasks:

* Map Utils label goes off screen to the right
* Identify and add the additional elements we might want

![screenshot from 2016-12-15 12 06 27](https://cloud.githubusercontent.com/assets/1014341/21233932/0eede5b8-c2bf-11e6-96d1-5d28181cac16.png)

**Comment by kdeloach** [comment]
The "Help" text needs to be translated for Spanish regions. I also noticed that the tour does not appear for the Spanish region (on Jenkins, at least).
