### ISSUE TITLE
Map utils dropdown appears behind the map legend

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#791]
![screenshot 2016-12-15 at 15 31 24](https://cloud.githubusercontent.com/assets/43062/21240981/b6c0bd12-c2db-11e6-8a68-09eb5b927996.png)

**Comment by mmcfarland** [comment]
Shares a point with #797

**Comment by rajadain** [comment]
How can I get the map utils icon to show up? It isn't visible by default

**Comment by kellyi** [comment]
I think it's the wrench now:

![screen shot 2016-12-22 at 3 03 27 pm](https://cloud.githubusercontent.com/assets/4165523/21438580/cee62d06-c857-11e6-9488-bbe5686c5253.png)

**Comment by rajadain** [comment]
Ah, thanks.
