### ISSUE TITLE
Style active app in navigation

### ISSUE THREAD

**Issue by jfrankl** [CoastalResilienceNetwork/GeositeFramework#792]
In the lefthand app navigation, we want the currently open app to have a different background color than other active apps. A recent pull request added the `.app-displayed` class to this button. Adding a color for this state is made complicated by the color customization for this application. The `.app-displayed` color could be:

1. A custom property set like the other colors in the application
2. Generated as a lighter or darker version of the of the primary color

That first option looks best to me—@kdeloach, let me know what you think.

![image](https://cloud.githubusercontent.com/assets/1809908/21241601/55cae73c-c2de-11e6-86bb-82c94e437a3f.png)

**Comment by kdeloach** [comment]
First option would probably look better, but it would add another mandatory(?) configuration option per region. We may have to stick with the second option.

@ajrobbins ^

**Comment by jfrankl** [comment]
@mmcfarland Kevin said you might be the person to ask about this. Any insight?

**Comment by ajrobbins** [comment]
Just chatted with @mmcfarland about this - we should go with option #1, but provide an initial configuration option for what looks best on Coastal Resilience (@jfrankl)
