### ISSUE TITLE
Plugin controls in app headers aren't clickable in IE11

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#807]
Observed in IE 11 on Windows 10:
Plugin controls (minimize, close, print) aren't clickable.

**Comment by kellyi** [comment]
Checked this out in IE11 and this is happening because the `.sidebar` class has a Z-index of 2000, which forces to sit above the buttons and prevents clicks or mouseover events from passing through.
