### ISSUE TITLE
"Physical" basemap doesn't appear

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#810]
Selecting the "Physical" ESRI basemap from the basemap selector leads to a black map

**Comment by kellyi** [comment]
I checked this on desktop and iOS Safari and the "Physical" basemap looks like it's working now. Going to close this; we can reopen if we encounter the problem again.

**Comment by mmcfarland** [comment]
Just ran into this again, but it's because the Physical basemap doesn't go in past zoom level 8.  This behavior is the same on the old/existing production sites.  Going to leave the issue closed.
