### ISSUE TITLE
UI Issues on Nexus tablets

### ISSUE THREAD

**Issue by kellyi** [CoastalResilienceNetwork/GeositeFramework#825]
In #771 we updated the app's CSS and functionality to improve the tablet-size UI for iPad Safari. Some of the changes related to viewport size should fix the appearance on all 10" sized tablets, such as the changes made to how the tooltips and the plugin list sidebar works on narrow viewports.

This card is for cataloguing and fixing Nexus/Chrome issues not resolved by work done in #771 or cards spun off from it.

**Comment by caseycesari** [comment]
Since no issues were added to this, and the purpose of the card was to catalog issues, I'm going to close this. We can add Nexus issues individually if they come up.
