### ISSUE TITLE
Final prototype branch feedback (0 pts)

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#827]
Feedback to come out of 1/11 demo of final prototype version and styleguide.

Originally 3pts

**Comment by mmcfarland** [comment]
Distributed to #833 and #834

**Comment by mmcfarland** [comment]
Currently, the list is:

[ ] Launchpad scrolling behavior across all browsers

**Comment by lewfish** [comment]
> Currently, the list is:
> 
>  Launchpad scrolling behavior across all browsers

I cannot replicate this on the prototype branch.

**Comment by lewfish** [comment]
This problem happens when running http://jenkins01.internal.azavea.com/view/TNC/job/TNC%20NY%20(prototype)/ but doesn't happen when running the project locally with only the regional planning plugin added.

**Comment by lewfish** [comment]
> Currently, the list is:
> 
>  Launchpad scrolling behavior across all browsers

I am going to try to fix scrolling in the regional planning plugin (as part of https://github.com/CoastalResilienceNetwork/regional-planning/issues/63), and hopefully that will fix this too. So I wouldn't work on this as a separate card.

**Comment by lewfish** [comment]
Scrolling was fixed by Jeff in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/848

**Comment by rajadain** [comment]
-1 to #855

**Comment by kellyi** [comment]
-1 for #856

**Comment by kellyi** [comment]
-1 for #858
