### ISSUE TITLE
Create experimental JSAPI 4.0 branch

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#828]
We'll be doing some work that doesn't have an explicit path to be merged into master, based off of the prototype branch.  This will involve upgrading the ESRI API to the most recent 4.x series and getting it working "basically", where "basically" will mean major features will work (map, adding layers), but it does not need to be universally complete.  In fact, the API is not even feature complete with the 3.x series, so it may not be possible to.

**Comment by kellyi** [comment]
Fork is here: https://github.com/CoastalResilienceNetwork/GeositeFramework/tree/js-api-4x-pilot

**Comment by kellyi** [comment]
It appears that the JS Web Optimizer is not available for building bundles using the 4.x API, so I'm going to start out by including the JS & CSS from a CDN.

**Comment by kellyi** [comment]
Upgraded to 4.2 using the CDN and there were about 15 immediate issues related to breaking API changes. I was able to resolve the following issues by renaming imports or adjusting directory paths:

- `esri/dijit/Popup` is now imported from `esri/widgets/Popup`
- `ArcGISTilerMapServiceLayer` is now `TileLayer`
- `esri/map` is now `esri/Map`
- `esri/SpatialReference` is now imported from `esri/geometry/SpatialReference`
- `esri/InfoTemplate` is now `esri/PopupTemplate`
- `esri/graphic` is now `esri/Graphic`
- `esri/dijit/Search` is now imported from `esri/widgets/Search`
- `ArcGISDynamicMapServiceLayer` is now `MapImageLayer`
- `esri/tasks/IdentifyParamter` is now imported from `esri/tasks/support/IdentifyParameter`
- `esri/geometry/webMercatorUtils` is now imported from `esri/geometry/support/webMercatorUtils`

The following errors are going to take slightly more work to resolve as they're related to features not yet implemented in 4.x or features which aren't going to be implemented in 4.x per this reference: https://developers.arcgis.com/javascript/latest/guide/functionality-matrix/index.html

- `esri/dijit/Scalebar` is "Coming soon"
- `esri/geometry/geodesicUtils` is "Coming soon"
- `esri/geometry/mathUtils` is "Not planned"
- `esri/units` is "Not planned", although the API docs suggest an alternate way to handle it
- `estri/dijit/InfoWindow` is "Not planned"; the API docs recommend using `View.popup` instead

Going to pull in the regional planning plugin and see if it has any additional errors.

**Comment by kellyi** [comment]
New regional-planning branch for the upgrade is here:

https://github.com/CoastalResilienceNetwork/regional-planning/tree/js-api-4x-pilot

**Comment by kellyi** [comment]
After updating regional-planning with some name changes, it looks like there are four issues remaining:

- `WMSLayer` support is "Coming soon"
- `LayerDrawingOptions` is "Coming soon"
- `toolbars/Draw` is "Coming soon"
- `esri/nls/jsapi` is not documented in the functionality matrix: https://developers.arcgis.com/javascript/latest/guide/functionality-matrix/index.html

**Comment by kellyi** [comment]
I've commented out or otherwise disabled most of the pieces without an immediate upgrade path, and I'm going to work on getting the tile layers which should be working to load. It seems like that might require setting up the map within a `MapView` -- 

https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html

-- so I'm going to try to set that up.

**Comment by kellyi** [comment]
Got a `MapView` set up, albeit currently with no tools:

<img width="1049" alt="screen shot 2017-01-10 at 12 08 46 pm" src="https://cloud.githubusercontent.com/assets/4165523/21816303/b282a808-d72d-11e6-8244-ba3fd9f744ac.png">

Will now try re-connecting the basemap selector and wiring up the regional planning layers.

**Comment by kellyi** [comment]
Basemap selector is working:

![screen shot 2017-01-10 at 3 34 50 pm](https://cloud.githubusercontent.com/assets/4165523/21823727/66abe558-d74a-11e6-88a0-8f489666a842.png)

&

![screen shot 2017-01-10 at 3 34 40 pm](https://cloud.githubusercontent.com/assets/4165523/21823754/7a47f05c-d74a-11e6-88eb-fce02614c020.png)

**Comment by kellyi** [comment]
Got the plugins to initialize properly:

![screen shot 2017-01-11 at 9 33 01 am](https://cloud.githubusercontent.com/assets/4165523/21852432/ffb870e0-d7e0-11e6-9b83-92d2470721d5.png)

The `esri/request` API was changed in 4.x...

https://developers.arcgis.com/javascript/3/jsapi/esri.request-amd.html

vs.

https://developers.arcgis.com/javascript/latest/api-reference/esri-request.html

...so this utility function will probably have to be adjusted:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/js-api-4x-pilot/src/GeositeFramework/js/util/ajax.js

Will try updating that now.

**Comment by kellyi** [comment]
Made some adjustments to the utility function and the `regional-planning` plugin and was able to get a few of the plugins layers to render:

![screen shot 2017-01-11 at 11 32 36 am](https://cloud.githubusercontent.com/assets/4165523/21856965/c949ca0c-d7f1-11e6-84d5-516b6e54d66b.png)

The layers which currently work are:
- Inundation Depth
- Final FEMA Surge Area - February 2013
- Hurricane Sandy - County Impact Analysis

The rest of the layers seem to be making requests, but returning empty overlays. For the ones which aren't working, it seems like a common denominator is that they query string params for the `export?bbox=` request includes:

```
layers: show:-1
```

while the working layers seem to include

```
layers: show: [0,2]
```

...or similar.

**Comment by kellyi** [comment]
re: Layers: looks like it must not be setting them somewhere correctly. The Hurricane Sandy layers option ends up retrieving sublayers [0, 2], while it looks like in a deployed version of the prototype it's only getting sublayer 2. The other dynamic layers are showing up as -1, so I assume there's some kind of `find` or `findIndex` check which partly succeeds for the Hurricane Sandy layer (with one extraneous match), and does not succeed for the other layers).
