### ISSUE TITLE
Error when loading framework without any plugins

### ISSUE THREAD

**Issue by kellyi** [CoastalResilienceNetwork/GeositeFramework#830]
When loading the framework without any plugins (and, actually, I think, without any map services), the console logs the following error:

![map-error](https://cloud.githubusercontent.com/assets/4165523/21782674/3f7b21a6-d682-11e6-92f4-4693c682130a.png)

The error can be circumvented by including regional-planning or another plugin which pulls in layers from map servers, but we should fix it to accommodate loading a map with no services.

**Comment by kdeloach** [comment]
One idea that I had to fix this is to refactor the core framework to fully support AMD modules (there's only partial support right now). This would fix the bug but it's a non-trivial amount of work.

**Comment by caseycesari** [comment]
Closing because this isn't really applicable since at least one plugin is always included in the framework.
