### ISSUE TITLE
Create pilot region

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#846]
Create a pilot region built from the js-pilot branch; include pinned regional-planning of the same vintage

**Comment by kellyi** [comment]
I created a `js-api-4x-pilot` branch for the NY region -- https://github.com/CoastalResilienceNetwork/ny-prototype-region/tree/js-api-4x-pilot -- and set up a new job to build it on Jenkins.

The branch doesn't currently have the code addressing #844 or #845, but I'll pull those in when they're merged.

**Comment by mmcfarland** [comment]
We actually have a specific region in mind that we're targeting for the 4.0 pilot:  https://github.com/CoastalResilienceNetwork/pugetsound-region

**Comment by kellyi** [comment]
Sounds good. I'll make a new job using that one.

**Comment by kellyi** [comment]
I set up a Jenkins job to build this branch from the `pugetsound-region` setup:

https://github.com/CoastalResilienceNetwork/pugetsound-region/tree/js-api-4x-pilot

That one uses a service which already has dynamic map layers turned on, so the layer toggling works.

**Comment by kellyi** [comment]
That branch now pulls in the basemap and sublayer updates from #844 and #845 and has its launchpad configured to match the new API and show a link to the regional-planning plugin.
