### ISSUE TITLE
Initially select contents of Save & Share text box

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#852]
* Rename Help -> Tour, including translation files.
![screenshot 2017-01-24 at 2 00 54 pm](https://cloud.githubusercontent.com/assets/1014341/22262094/9218d6bc-e23d-11e6-8bef-cea34cb690d5.png)

* Initially select contents of Save & Share text box.  I'm fairly sure that this was prior behavior that recently broke.
![screenshot 2017-01-24 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/1014341/22262158/c9f5aa2e-e23d-11e6-8132-38106a4f1756.png)

**Comment by kellyi** [comment]
Renamed "Help" -> "Tour" in #863; still working on the Save & Share box.

**Comment by kellyi** [comment]
Renamed this issue to highlight the second item.
