### ISSUE TITLE
Change behavior of deactivated plugin

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#856]
Currently, when any plugin is deactivated other than by the `X` button, it will keep data layers on and hibernate - the same behavior as when the user clicks the minimize `_` button.  Modify the behavior such that switching between plugins has the same behavior as `X` and fully closes down the plugin.  This is essentially the same behavior that has forced in for "Get Started"/Launchpad - so we may be able to take that one-off and codify as regular behavior.  The minimize button should remain and operate as normal, but that is the only path to activate that behavior.

**Comment by kellyi** [comment]
Should closing a plugin sidebar by clicking on the plugin icon in the list on the left be handled as a "minimize" event or a "turn off" event? For example, if regional-planning is open...

<img width="1032" alt="screen shot 2017-01-25 at 10 29 26 am" src="https://cloud.githubusercontent.com/assets/4165523/22296836/687d52b8-e2e9-11e6-8c49-1d1330a74819.png">

... and I click on the "Regional Planning" in the plugin list, should it minimize and keep the layers and close altogether?

<img width="1031" alt="screen shot 2017-01-25 at 10 29 40 am" src="https://cloud.githubusercontent.com/assets/4165523/22296885/8e13fa7c-e2e9-11e6-923e-52693a12a95a.png">

**Comment by ajrobbins** [comment]
@kellyi I think it should minimize.

**Comment by kellyi** [comment]
Thanks @ajrobbins. One more q: If a plugin is minimized, and then I select another plugin, should the minimized plugin close? It seems like selecting a new plugin from the list when one is already open and has its sidebar visible/isn't minimized should close the open one; should it work the same way if a plugin is open and minimized?

**Comment by ajrobbins** [comment]
Yes, given the behavior we're implementing when the sidebar is open, I think selecting another plugin should close the open & minimized one.

**Comment by ajrobbins** [comment]
Closing the minimized plugin would make sense, but then there would be no way to have multiple apps open (and data layers on) at once at all. So I think it should stay open.

**Comment by ajrobbins** [comment]
@kellyi Just got word from Zach that we can keep the existing behavior of deactivated plugins. Sorry for the trouble - thanks for working on this, we should close and not merge.
