### ISSUE TITLE
Add titleDetail to header

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#858]
With #853, we'll be losing the region name from the header for Coastal Resilience sites. Add a configurable second header to the header that looks the same as the old header did, but isn't a drop down:

![screen shot 2017-01-25 at 9 33 51 am](https://cloud.githubusercontent.com/assets/12868342/22294506/88c97cf2-e2e1-11e6-9fb1-310798125dca.png)

**Comment by mmcfarland** [comment]
For clarification, this isn't a second header element, but rather just a label showing a region name in the existing header.  I believe we already have a region.json config element, `titleDetail` which is being used as the display value portion of the existing dropdown, we'll probably just want to nix the dropdown control component.

**Comment by caseycesari** [comment]
The behavior of the region menu was that if no items were provided, the menu wasn't rendered but the subtitle still was. I'm not sure if that logic (and the DOM elements) are still in the code, though.
