### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#875]
Request from TNC:
- header background from #0f1C27 to #5394B6 (main.css line 857)
- nav-apps background from #27343E to #333333 (main.css line 787)
- font color defined for body from #73787D to #5d6165 (main.css line 441) - provides more contrast against a white background.
- selected radio, pills, and checkboxes background from #4b9CAF to #0096D6 (styleguide.css)
- primary button and slider handle background from #4b9CAF to #0096D6 (styleguide.css)

**Comment by caseycesari** [comment]
Shares a point with #872

**Comment by caseycesari** [comment]
Shares a point with #872
