### ISSUE TITLE
Show plugin sidebar X buttons without hover

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#877]
With https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/870, we are showing an X button for active yet minimized apps in the sidebar menu on hover. TNC wants us to have this button display at all times for active yet minimized apps, not just on hover. This will make the feature more easily discoverable by users.

**Comment by kellyi** [comment]
Should the close icon button also display for active, non-minimized plugins?

![screen shot 2017-02-15 at 6 12 03 pm](https://cloud.githubusercontent.com/assets/4165523/22999606/563f5674-f3aa-11e6-9bd1-0c101473eea6.png)

**Comment by mmcfarland** [comment]
Nope, maintain the existing behavior for that.  Still just minimized.

**Comment by kellyi** [comment]
Shares a point with #871

**Comment by kellyi** [comment]
Shares a point with #882 too
