### ISSUE TITLE
Plugin close button is visible for active, minimized apps when sidebar is minimized

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#882]
![image](https://cloud.githubusercontent.com/assets/1042475/23079716/0d1e61a6-f51c-11e6-8002-bb956dd5ad59.png)

I believe this was introduced in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/879, now that the close button is shown without needing to hover. We should hide it when the sidebar is minimized.

**Comment by kellyi** [comment]
Shares a point with #877

**Comment by kellyi** [comment]
This seemed to be happening because the `:hover` postfix was still attached to this line:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/css/main.css#L872
