### ISSUE TITLE
Deemphasize search control

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#886]
Feedback from TNC:

>De-emphasize Search: smaller window on default, even as dark blue until user clicks inside find address.

**Comment by mmcfarland** [comment]
For context, this is an example being referred to
![screenshot from 2017-02-20 10 42 43](https://cloud.githubusercontent.com/assets/1014341/23131810/72fb2b00-f759-11e6-88cb-2c4425430002.png)

`Search Mail` becomes an input when you click on it.

**Comment by caseycesari** [comment]
We could use the built-in collapse mode for the search control

Demo: https://jsbin.com/jukinehiru/edit?html,output
