### ISSUE TITLE
Add example of using image in modal

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#888]
In a sample app, show how to use TINY to make an image viewer for a full size image from a thumbnail (css resized, can be the same actual image).   

Try using an infographic from the old app as it's likely what they'll want to use this on.
http://maps.coastalresilience.org/gulfmex/plugins/future_habitat/FutureHabitat_c.jpg

 Add a snippet of this code to the wiki, as well.

**Comment by kellyi** [comment]
Updated the wiki's Plugin Settings page with instructions for creating a modal here:

https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Plugin-Settings
