### ISSUE TITLE
Support (0pts)

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#894]
Started at 3pts

**Comment by caseycesari** [comment]
-1 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/898

**Comment by caseycesari** [comment]
-1 for https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/900

**Comment by mmcfarland** [comment]
-1 for #903
