### ISSUE TITLE
Add IIS configuration to serve woff2 files

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#895]
When the `mantle.woff2` file is requested, a `404 Not Found` response is received. 

If you request the file directly (`http://localhost:54633/fonts/fontello/font/mantle.woff2`), the following message is returned:

> The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

When requesting a different format of the font file, the file is downloaded (example: `http://localhost:54633/fonts/fontello/font/mantle.woff`).

We should configure IIS (and the VS dev server, ideally) to serve `.woff2` files.

This SO answer has a fix, but I was unable to get it to work in a quick implementation: http://stackoverflow.com/a/28955302/217378

**Comment by mmcfarland** [comment]
Would be great to have this configuration provided in the web.config so that the TNC servers would pick up the change automatically.

**Comment by mmcfarland** [comment]
Closing as we're moving away from IIS hosting
