### ISSUE TITLE
Make sure Chosen, JQueryUI are available to plugins

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#903]
Two JS libraries (Chose & JQueryUI) were added to the framework to support styleguide features but may not be globally available.  Add two components (slider & chosen select) to the sample app and make sure the framework supports their being called either globally or within the `use` statement.

**Comment by kellyi** [comment]
Was looking at how the i18-next library's set up, and it looks like it gets initialized in App.js by adding it to jQuery. Tried out a similar `addChosen` method and it looks like we can add it there and make it available to plugins:

https://github.com/CoastalResilienceNetwork/GeositeFramework/commit/ae1cf0f5f9f67a5f29054bcbc74127fcad4e3257

->

![screen shot 2017-03-07 at 5 27 29 pm](https://cloud.githubusercontent.com/assets/4165523/23681038/5d02dce0-035b-11e7-8258-b53878dcccdf.png)

Prior to that, however, $ doesn't have `.chosen` attached. Going to see about manually attaching it either here or somewhere else in the hierarchy.
