### ISSUE TITLE
Add button to toggle 3d mode

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#909]
Currently an app can toggle 3d mode, but the app should have its own toggle.  This will allow regions without the special plugin to activate the view and use regional-planning layers in 3d.

**Comment by kellyi** [comment]
Would it be preferable to add this as a wholly new map control or instead as an option on the existing Map Utils control popup?

**Comment by mmcfarland** [comment]
Due to the nature of this being for demoing that functionality specifically, I think a certain amount of prominence is a good idea.  I'd make it it's own thing.

**Comment by kellyi** [comment]
Sounds good. I'm going to add this as a framework plugin akin to `subregion-toggle`.
