### ISSUE TITLE
Make a wiki page for any required js-pilot changes to a region

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#911]
* Vector tile basemap shortcodes
* Enable dynamic layers for regional planning
* Build instructions

**Comment by mmcfarland** [comment]
Shares a point with #909

**Comment by kellyi** [comment]
Page is here:

https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Updating-a-Region-for-the-ArcGIS-JavaScript-API-4.x-Pilot

Let me know if it needs and adjustments or additions.

**Comment by mmcfarland** [comment]
+1, Page looks good

**Comment by kellyi** [comment]
Thanks!
