### ISSUE TITLE
Fix "Object doesn't support this action" error in IE

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#917]
The framework fails to load in IE11 on the latest `develop`.

![image](https://cloud.githubusercontent.com/assets/1042475/23804041/8e4eee2e-0586-11e7-98a4-f645fb7fdab2.png)

The [line of code](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Pane.js#L21) it is referencing hasn't been updated in a year, and the app worked in IE within the last couple months.

**Comment by caseycesari** [comment]
A similar error happens in Chrome if you checkout an earlier commit in `develop`, like 39c20c3

![image](https://cloud.githubusercontent.com/assets/1042475/23804259/4a15029c-0587-11e7-87c3-2bac2c923bf9.png)

**Comment by caseycesari** [comment]
Doing a `git bisect` points to ebb7e6045e64e3ee0061804000b22f51c45e288f as the breaking commit.

**Comment by caseycesari** [comment]
If you inspect `N.models.Map` in `pane.js`, it is undefined. Not requiring and initializing the map utils plugin in `Map.js` fixes the app in Chrome while ebb7e60 is checked out. Requiring these plugins in `Map.js` may push the initialization of the `Map` module until some other parts of the framework are ready (because of some dependency of one of the plugins), which means it's not defined when `Pane.js` tries to create a `map`.

This also fixes the app in IE on `develop`. 

I'm next going to check how the app became fixed in Chrome even though the map util plugins are still being required.

**Comment by caseycesari** [comment]
It also may be worth noting that I don't have the regional planning plugin installed in my local framework. This may have somehow been preventing this error, like it was preventing https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/910.

**Comment by caseycesari** [comment]
It appears that this error was fixed in Chrome by 8fc55b1282d0a9eb2ddb1c4fb375bada27e1f543.

**Comment by caseycesari** [comment]
I tried delaying the initialization of the map in `Pane.js` with a `setTimeout`, but this causes other problems.

**Comment by kellyi** [comment]
Checked this in Safari and Firefox without any plugins and both of them work (as does Chrome). Investigating IE.

**Comment by kellyi** [comment]
In IE11 `N.models` doesn't have a Map key when this line gets executed:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/Pane.js#L21

Compare with Chrome:

<img width="242" alt="screen shot 2017-03-13 at 3 57 30 pm" src="https://cloud.githubusercontent.com/assets/4165523/23872731/ca2dc72c-0805-11e7-9ee0-bead43b3cb4c.png">

**Comment by kdeloach** [comment]
There are several possible race conditions that may occur because half of the core framework is not fully AMD compliant. Notice that although Pane.js is an AMD module it doesn't "require" Map as a dependency, so the execution order isn't guaranteed. I noticed this race condition happens when no plugins are installed. The workaround (at the time) was to add at least one plugin.

**Comment by kellyi** [comment]
Oof. Ok, so it looks like:

1. Without any plugins, the site throws an `N.models.Map is not a constructor` error in Chrome if the changes from #906 (and later #916) are not included in the branch

2. Without any plugins, the site seems to work in IE11 **unless* the changes from #906 (and #916) are not included the branch.

Both of these are probably still just symptoms of the underlying issue.

**Comment by kellyi** [comment]
Making a note to try importing the new jQuery libraries in the plugins themselves rather than in PluginBase and see if that makes a difference.

**Comment by kellyi** [comment]
Confirmed that moving the library imports does not help.

**Comment by kellyi** [comment]
I set breakpoints here in Pane.js:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Pane.js#L15

and here in Map.js:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Map.js#L47

...in both Chrome and IE. This probably confirms what we already know but in Chrome the code from `Map.js` gets hit first, while in IE the code in `Pane.js` gets hit first. Going to check out the call stack for each.

**Comment by kellyi** [comment]
Here's IE:

![screen shot 2017-03-14 at 11 16 20 am](https://cloud.githubusercontent.com/assets/4165523/23907485/b10dd5b4-08a7-11e7-8638-4277da6fdd0a.png)

Chrome goes through dojo:

![screen shot 2017-03-14 at 11 17 07 am](https://cloud.githubusercontent.com/assets/4165523/23907526/d2b7fde8-08a7-11e7-91cf-c1f4e8fbaca2.png)

**Comment by kellyi** [comment]
Put a breakpoint in PluginBase.js for each at the return statement in the initializer:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/b92f2c70f05ec8cc26f2bdb667401498c59d548b/src/GeositeFramework/js/PluginBase.js#L32

IE hits the PluginBase line first; Chrome still hits the `N.models` line where the map's initialized first.

**Comment by kellyi** [comment]
Commenting out these three lines:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/Map.js#L6

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/Map.js#L17

&

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/Map.js#L155

Enables the app to load in both IE and Chrome, but breaks the map tools. Going to see if there's another way to wire them up which wouldn't impede `N.models.Map` being created.

**Comment by kellyi** [comment]
Drilled down to the utils and it looks like commenting out the Measure util imports starting here:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/widgets/map_utils/main.js#L4

Fixes the issue in both IE and Chrome. Looks like the Measure utility might take some amount of time to set up, and it may be making an ajax request to an ArcGIS url:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/widgets/map_utils/measure/AgsMeasure.js

Going to see if I can reduce the amount of time it takes to set up.

**Comment by kellyi** [comment]
Appears that dropping this `jquery` import -- https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/widgets/map_utils/measure/AgsMeasure.js#L3 -- and just relying on the global `$` remedies the timing issue in IE, keeps Chrome still working, and allows the measure tool to work as usual.
