### ISSUE TITLE
Investigate `supressHelp` usage

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#932]
There may be an implementation error that doesn't allow this property to be reset.

> How do you set showHelpOnStart to true? I get that passing true to supressHelpOnStartup sets showHelpOnStart to false, but if I pass false to supressHelpOnStartup it doesn’t change showHelpOnStart

![image](https://cloud.githubusercontent.com/assets/1014341/24251104/68c1cc5c-0faf-11e7-915d-c29b279d4a4d.png)

**Comment by kellyi** [comment]
Looks as if we're passing the value set in localStorage for `suppressHelpOnStartup` into the plugin to activate it:

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Plugin.js#L197

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/Plugin.js#L297

Going to step through the checks to see what's happening.
