### ISSUE TITLE
Slim down nav-apps sidebar

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#936]
TNC is requesting that we reduce the fixed width of the app menu sidebar. It's currently at 240px; I think we could take it down to 220px:

![screen shot 2017-03-30 at 11 00 41 am](https://cloud.githubusercontent.com/assets/12868342/24510809/32a50eac-1538-11e7-8573-de276eba2b57.png)

cc @jfrankl

**Comment by jfrankl** [comment]
+1
