### ISSUE TITLE
Move sidebar collapse control closer to sidebar

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#937]
We created a sidebar collapse button (really, map expand) and put it under similarly styled map controls on the right side of the screen:

![screen shot 2017-03-30 at 11 02 07 am](https://cloud.githubusercontent.com/assets/12868342/24510885/6607e2f6-1538-11e7-9060-344c2d3f75a5.png)

In testing, it's proving difficult for users to discover this easily and associate with collapsing the sidebar, which is a desired use case. We should move the control closer to the sidebar and potentially restyle it. I'm thinking of something along these lines (from Waffle):

![screen shot 2017-03-30 at 11 04 26 am](https://cloud.githubusercontent.com/assets/12868342/24510975/a9ef7038-1538-11e7-9300-3718a308ac5d.png)

**Comment by ajrobbins** [comment]
@jfrankl design to implement:

![pasted image at 2017_03_31 04_08 pm](https://cloud.githubusercontent.com/assets/12868342/24611810/4e29d5ce-1851-11e7-8bba-e9fa4acf4c24.png)

**Comment by zferdana** [comment]
I like the thinking and design here. Upon more discussions with the team, we are thinking it might be best to have the sidebar collapsed (just icons showing) upon entering a region. That forces the user to read Get Started and click on a Go link that then expands the sidebar and therefore shows the list of apps and titles. What do you think?

**Comment by jfrankl** [comment]
I’d say that when a user comes to the application for the first time, that’s when the app labels are going to be most important for getting context about what the application can do and how they want to start using it. It is a common design pattern to show all labels and identifying text when the application loads, possibly hiding that information once a user digs deeper into the application. 

I understand the desire to have users read the Get Started text. However, individuals have different learning styles and approaches to applications—some people like to read instructions and others like to try clicking around. Some people will not read help text no matter what we do, and we want to make sure they can find their way around.

I think the full app sidebar should be available when the user first loads the application, and they will be able to close it by clicking on the collapse button if they want to hide it.

**Comment by ajrobbins** [comment]
@zferdana thoughts on the above?

**Comment by zferdana** [comment]
Jeff and Arianna- thanks for the comments. I have discussed this with our core tech team and this is the desired, default behavior that we want: have sidebar collapsed at all times. So this means on default only app icons show, and Get Started is open. Then when a user hits a Go link it opens an app, but the sidebar is still closed. Then the user has the ability to open the sidebar with the new placement of the toggle button (which is great, BTW). We would like this to be implemented now for testing with project teams and stakeholders. We assume this is an easy behavior to change (let us know if not!); Get Started will be the initial screen that introduces the apps, with short explanation, so no need to have sidebar open.
