### ISSUE TITLE
Regional Planning spawned plugins referencing wrong main.js

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/GeositeFramework#950]
In instances where Regional Planning is imported for other plugins (See http://dev.maps.oceanwealth.org blue-carbon), code in the regional planning plugin is being referenced by that plugin resulting in a number of functionality errors.  Specifically, the zoomToLayerExtent is incorrectly bound in the blue-carbon plugin (which inherits regional planning code) and fails given that the tree object's findLayer method actually references the regional-planning plugin/object thus the layer variable returns undefined (i.e. not found) and subsequently fails on layer.getService().

**Comment by zferdana** [comment]
Great catch Erik! Arianna - seems we should address this as we dropped our Get Started customization task. Didn't know it would be replaced so quickly! Let us know if this issue is better served in the regional-planning repo, thanks

**Comment by mmcfarland** [comment]
@enlowe outside of the Zoom To and Transparency menu controls, did you find any other behavior where events weren't bound correctly?

**Comment by enlowe** [comment]
From what we encountered ourselves and what users reported to us, this was the only behavior

**Comment by mmcfarland** [comment]
Thanks, @enlowe.  If you rebuild using the latest `regional-planning` plugin, this issue should be resolved.
