### ISSUE TITLE
Updating Chosen library

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#960]
Update the Chosen library in the framework so it works with mobile. Issue was seen with a Samsung Galaxy Tab A with all the app pull downs and app toolbar disappearing. This was tested with the maps.coastalresilience.org/northcarolina site, and the CRS app

**Comment by ajrobbins** [comment]
Closed via https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/961
