### ISSUE TITLE
Investigate custom print inconsistencies

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#963]

**Comment by ajrobbins** [comment]
See powerpoint of examples 
[2017_06_28_Print_Issues.pptx](https://github.com/CoastalResilienceNetwork/GeositeFramework/files/1125966/2017_06_28_Print_Issues.pptx)

**Comment by caseycesari** [comment]
Currently, when the print legend is assembled, custom plugin legends are ignored. It shouldn't be too difficult to modify the code to include these legends. However, most of them are constructed using SVG, which will be difficult to reflow/reorganize for printing. I think we should see if the custom plugin legends could be accommodated by the new built-in legend types, and if not, add more types if needed.
