### ISSUE TITLE
no search on cities application

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#989]
http://dev.maps.coastalresilience.org/cities/ - don't see the Search bar on this application, not sure why...

**Comment by caseycesari** [comment]
The [Natural Defenses plugin](https://github.com/CoastalResilienceNetwork/natural_defenses) is hiding the search element: 

https://github.com/CoastalResilienceNetwork/natural_defenses/blob/bf978774bb2456dff343eed233d87d6f9c7c9517/css/main.css#L1-L3

**Comment by cschneebeck** [comment]
My recollection is that there was a request to hide it.

Casey Schneebeck



On Tue, Sep 19, 2017 at 7:55 AM -0600, "Casey Cesari" <notifications@github.com<mailto:notifications@github.com>> wrote:


The Natural Defenses plugin<https://github.com/CoastalResilienceNetwork/natural_defenses> is hiding the search element:

https://github.com/CoastalResilienceNetwork/natural_defenses/blob/bf978774bb2456dff343eed233d87d6f9c7c9517/css/main.css#L1-L3<https://github.com/CoastalResilienceNetwork/natural_defenses/blob/bf978774bb2456dff343eed233d87d6f9c7c9517/css/main.css#L1-L3>

-

**Comment by zferdana** [comment]
Ok, thanks for the clarification, Casey S. I would go ahead and turn it back on for consistency across applications, unless you see a compelling reason to keep it hidden - thanks Zach

**Comment by caseycesari** [comment]
Going to close this since it's not an issue with the core framework.
